### ISSUE TITLE
Checkout: Error when trying to remove 'Domain Late Renewal Fee'

### ISSUE THREAD

**Issue by klimeryk** [Automattic/wp-calypso#13087]
#### Steps to reproduce
1. Starting at URL: `/me/purchases`
2. Select a domain that has expired (probably longer than 19 days, so that the `Domain Late Renewal Fee` applies).
3. Click `Renew Now`.
4. Get redirected to checkout with three items in your cart, including the `Domain Late Renewal Fee`, which has an `x` that is tempting to click - so I click it.

#### What I expected
First of all - the `x` should not be there, since the `Domain Late Renewal Fee` is not optional at this point ;)

#### What happened instead
When I clicked the `x`, I got an error in the console:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object (native)
    at eval (app:///./~/lodash/_createAssigner.js:26:14)
    at apply (app:///./~/lodash/_apply.js:15:25)
    at eval (app:///./~/lodash/_baseRest.js:31:12)
    at formatProduct (app:///./client/lib/products-values/index.js:48:9)
    at isDependentProduct (app:///./client/lib/products-values/index.js:237:12)
    at eval (app:///./client/lib/cart-values/cart-items.js:197:10)
    at Array.filter (native)
    at getDependentProducts (app:///./client/lib/cart-values/cart-items.js:196:39)
    at eval (app:///./client/lib/cart-values/cart-items.js:201:10)
```

Additionally, I can't remove the domain from the cart either. Reloading the page doesn't work either. The only way to clear the cart is to add a regular domain to it that will override the cart's contents.

#### Browser / OS version
OSX / Chromium	59.0.3031.0 - the above error
OSX / Safari 10 - the tab hangs

#### Screenshot / Video
<img width="267" alt="screen shot 2017-04-13 at 15 57 23" src="https://cloud.githubusercontent.com/assets/3392497/25007779/eb64acde-2061-11e7-8c9b-8d35ac1dc7af.png">

#### Context / Source
#dogfooding #manual-testing

**Comment by klimeryk** [comment]
cc @umurkontaci - seem the problematic function here is `getDependentProducts` you've introduced some time ago.
