### ISSUE TITLE
npm start error, could not locate the bindings file: leveldown.node

### ISSUE THREAD

**Issue by wufeng87** [Automattic/wp-calypso#16736]
node: 6.10.3
npm: 3.10.10
yarn: 0.24.5

```
> wp-calypso@0.17.0 prestart C:\code\ghub\wp-calypso
> npm run -s install-if-needed && node bin/welcome.js && ( check-node-version --package || exit 0 )

             _
    ___ __ _| |_   _ _ __  ___  ___
   / __/ _` | | | | | '_ \/ __|/ _ \
  | (_| (_| | | |_| | |_) \__ \ (_) |
   \___\__,_|_|\__, | .__/|___/\___/
               |___/|_|

node: 6.10.3
npm: 3.10.10
yarn: 0.24.5

> wp-calypso@0.17.0 start C:\code\ghub\wp-calypso
> npm run -s build

[[....................................] - : [] - : info..................info ] - :  usinginfo node@v6.10.3       node@v[[....................................] - : ] - : infoinfo [using[....................................] - : ] - : infoin[....................................] | : ] | : ] - : infoinfoinfoinfo   usingusing using node@v6.10.3
] | : ..................info[ ] / : using.................. node@v6.10.3      ..................info] - : infoinfo   usi..................[] / : ..................info] / : ..................info[ ..................] - :  infousing] - :  no[....................................] - : ] - : infoinfo  usingusing node@v6.10.3             
[
[..................o  [Rendering Complete, saving .css file..................... usingusing node@v6.10.3
] - : [infoRendering Complete, saving .css file...
 sing.................. node@v6.10.3      Wrote CSS to C:\code\ghub\wp-calypso\public\directly.cssinfo
usingWrote CSS to C:\code\ghub\wp-calypso\public\editor.css node@v6.10.3
[[....................................] - : ] | : infoinfo  usingusing node@v6.10.3              [using.................[[..................[] - : ..................info] | :  [info..................using] - :  node@v6.10.3      usingusing [....................................] - : ] | : infoinfo  usingusing node@v6.10.3                  ..................] ..................[] - : .................. ] / : infoinfo  usingusing node@v6.10.3                   node@v6.10.3
....................................] - : infoinfo[ [using] - : ..................info ] | : .................. node@v6.[[....................................] / : ] / : infoinfo  usingusing node@v6.10.3                               ......[ node@v6.10.3                  C:\code\ghub\wp-calypso\node_modules\_bindings@1.2.1@bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\build\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\build\Debug\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\build\Release\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\out\Debug\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\Debug\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\out\Release\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\Release\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\build\default\leveldown.node
 → C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\compiled\6.10.3\win32\x64\leveldown.node
    at bindings (C:\code\ghub\wp-calypso\node_modules\_bindings@1.2.1@bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\code\ghub\wp-calypso\node_modules\_leveldown@1.7.2@leveldown\leveldown.js:4:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\ghub\wp-calypso\node_modules\_level@1.7.0@level\level.js:1:106)
[ ..................using] - : events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at notFoundError (C:\code\ghub\wp-calypso\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\code\ghub\wp-calypso\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\code\ghub\wp-calypso\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[....................................] / : ] | : sillinfo  lifecycleusing wp-calypso@0.17.0~build-css:editor: Args: [ '/[[....................................] | : ] / : infosill  usinglifecycle node@v6.10.3
 ..................] / : infoBuilding: proptypes-index.json
[..................] - : info using node@v6.10.3
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
```

Best regards!

**Comment by alisterscott** [comment]
Hello, are you trying `npm start`? Can you please try `npm run distclean` first, and then `npm start` again?

**Comment by wufeng87** [comment]
thx, It's OK now.
