### ISSUE TITLE
Cannot find module "notifications-panel", the file is pre-built in the node_modules directory.

### ISSUE THREAD

**Issue by wufeng87** [Automattic/wp-calypso#16739]
![image](https://user-images.githubusercontent.com/1686808/28765726-c91a4f06-75fe-11e7-83ee-3f78977e6c0d.png)

When I run `npm start`， the error says the Notifications.jsx file is pre-built. 
how to build the src file in mode_modules?
Thanks.

**Comment by designsimply** [comment]
@wufeng87 can you post the exact text of the error please? (this is so we have it on record)

Also may I please ask why you want to build src file in mode_modules?

**Comment by wufeng87** [comment]
win10
node: 6.10.3
npm: 3.10.10
yarn: 0.24.5

```
ERROR in ./~/_notifications-panel@1.1.15@notifications-panel/src/Notifications.jsx
Module parse failed: C:\code\ghub\wp-calypso\node_modules\_notifications-panel@1.1.15@notifications-panel\src\Notifications.jsx Unexpected token (32:21)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (32:21)
    at Parser.pp$4.raise (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:603:10)
    at Parser.pp.expect (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:597:28)
    at Parser.pp$3.parseMethod (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:2071:10)
    at Parser.pp$1.parseClassMethod (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:1137:25)
    at Parser.pp$1.parseClass (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:1118:14)
    at Parser.pp$1.parseStatement (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:697:19)
    at Parser.pp$1.parseExport (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:1181:31)
    at Parser.pp$1.parseStatement (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:719:71)
    at Parser.pp$1.parseTopLevel (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:516:17)
    at Object.parse (C:\code\ghub\wp-calypso\node_modules\_acorn@3.3.0@acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\code\ghub\wp-calypso\node_modules\_webpack@1.13.1@webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\code\ghub\wp-calypso\node_modules\_webpack@1.13.1@webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\code\ghub\wp-calypso\node_modules\_webpack-core@0.6.9@webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\code\ghub\wp-calypso\node_modules\_webpack-core@0.6.9@webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\code\ghub\wp-calypso\node_modules\_webpack-core@0.6.9@webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\code\ghub\wp-calypso\node_modules\_enhanced-resolve@0.9.1@enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\code\ghub\wp-calypso\node_modules\_graceful-fs@4.1.11@graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
 @ ./client/notifications/index.jsx 60:26-56
```

**Comment by blowery** [comment]
Hi @wufeng87, 

Are you using `yarn` or `npm` to install the required packages? The path to the notifications panel looks a bit strange and we have a [special exemption in our webpack.config](https://github.com/Automattic/wp-calypso/blob/master/webpack.config.js#L87) to process notifications-panel with babel. Seems like the path you're seeing would break that exception. 

cc @dmsnell

**Comment by ockham** [comment]
> When I run `npm start`

That probably doesn't build Calypso (thus ES6 code isn't transpiled). Try `make run` instead, which should also invoke required building steps.

**Comment by dmsnell** [comment]
Yeah if we're trying to build `notifications-panel` from within the `node_modules` directory then I'm guessing it will fail on account of weird interactions with Babel and webpack. If we are running `npm start` from within the root Calypso directory it should all be fine. If we want to run the notifications panel separately then it's probably best to clone it in a separate directory and build it there by itself.

**Comment by wufeng87** [comment]
Thanks for your help.
@blowery yes, I ran a `cnpm install`  to install the required packages.
(`npm install -g cnpm --registry=https://registry.npm.taobao.org`)

I changed the exclude value of the babel loader config, and it works now:
`exclude: /node_modules[\/\\](?!_notifications-panel|notifications-panel)/,`
