### ISSUE TITLE
Windows: Can't boot Calypso

### ISSUE THREAD

**Issue by montacir** [Automattic/wp-calypso#19073]
Hello, 
I Tried to install wp-calypso project in my windows, then in ubuntu vm. I used nvm to set node version to 6.11.2 as mentionned in the README. 
when I executed npm start I got:
 Failed at the wp-calypso@0.17.0 prestart script 'npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )'.
Thank you.

**Comment by withinboredom** [comment]
What version of windows? Which console are you using (cmd, powershell, git bash, cmdr, linux for windows, etc)?

**Comment by montacir** [comment]
I am working in windows 10 with powershell and in a VM in ubuntu 16.
I enter the command: npm start.

**Comment by withinboredom** [comment]
Is your VM using a shared folder to access the files from the host machine? If so, you may be hitting the Windows filesystem path limits (which should be mitigated by this version of node/npm, but I still run into them from time to time).

I personally just install the node package specified in the build from Node, since sometimes the shell will pick the wrong version when using things like `n` or `nvm.` However, ymmv.

I'm also seeing a crash, but not in the same place you are, I'm seeing:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wp-calypso@0.17.0~prestart: wp-calypso@0.17.0
6 verbose lifecycle wp-calypso@0.17.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle wp-calypso@0.17.0~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\withi\Source\Repos\wp-calypso\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\iis express\PHP\v7.1;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\GitHubDesktop\bin
8 verbose lifecycle wp-calypso@0.17.0~prestart: CWD: C:\Users\withi\Source\Repos\wp-calypso
9 silly lifecycle wp-calypso@0.17.0~prestart: Args: [ '/d /s /c',
9 silly lifecycle   'npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )' ]
10 silly lifecycle wp-calypso@0.17.0~prestart: Returned: code: 0  signal: null
11 info lifecycle wp-calypso@0.17.0~start: wp-calypso@0.17.0
12 verbose lifecycle wp-calypso@0.17.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle wp-calypso@0.17.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\withi\Source\Repos\wp-calypso\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\iis express\PHP\v7.1;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\GitHubDesktop\bin
14 verbose lifecycle wp-calypso@0.17.0~start: CWD: C:\Users\withi\Source\Repos\wp-calypso
15 silly lifecycle wp-calypso@0.17.0~start: Args: [ '/d /s /c', 'npm run -s build' ]
16 silly lifecycle wp-calypso@0.17.0~start: Returned: code: 0  signal: null
17 info lifecycle wp-calypso@0.17.0~poststart: wp-calypso@0.17.0
18 verbose lifecycle wp-calypso@0.17.0~poststart: unsafe-perm in lifecycle true
19 verbose lifecycle wp-calypso@0.17.0~poststart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\withi\Source\Repos\wp-calypso\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\iis express\PHP\v7.1;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\Microsoft\WindowsApps;C:\Users\withi\AppData\Roaming\npm;C:\Users\withi\AppData\Local\GitHubDesktop\bin
20 verbose lifecycle wp-calypso@0.17.0~poststart: CWD: C:\Users\withi\Source\Repos\wp-calypso
21 silly lifecycle wp-calypso@0.17.0~poststart: Args: [ '/d /s /c',
21 silly lifecycle   'npm run -s env -- cross-env node $NODE_ARGS build/bundle.js' ]
22 silly lifecycle wp-calypso@0.17.0~poststart: Returned: code: 1  signal: null
23 info lifecycle wp-calypso@0.17.0~poststart: Failed to exec poststart script
24 verbose stack Error: wp-calypso@0.17.0 poststart: `npm run -s env -- cross-env node $NODE_ARGS build/bundle.js`
24 verbose stack Exit status 1
24 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at EventEmitter.emit (events.js:191:7)
24 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at ChildProcess.emit (events.js:191:7)
24 verbose stack     at maybeClose (internal/child_process.js:891:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
25 verbose pkgid wp-calypso@0.17.0
26 verbose cwd C:\Users\withi\Source\Repos\wp-calypso
27 error Windows_NT 10.0.15063
28 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
29 error node v6.11.0
30 error npm  v3.10.10
31 error code ELIFECYCLE
32 error wp-calypso@0.17.0 poststart: `npm run -s env -- cross-env node $NODE_ARGS build/bundle.js`
32 error Exit status 1
33 error Failed at the wp-calypso@0.17.0 poststart script 'npm run -s env -- cross-env node $NODE_ARGS build/bundle.js'.
33 error Make sure you have the latest version of node.js and npm installed.
33 error If you do, this is most likely a problem with the wp-calypso package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     npm run -s env -- cross-env node $NODE_ARGS build/bundle.js
33 error You can get information on how to open an issue for this project with:
33 error     npm bugs wp-calypso
33 error Or if that isn't available, you can get their info via:
33 error     npm owner ls wp-calypso
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]
```

**Comment by DanReyLop** [comment]
Duplicated of https://github.com/Automattic/wp-calypso/issues/16452, a fix is on its way.

See workaround: https://github.com/Automattic/wp-calypso/issues/16452#issuecomment-317970086
