### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by negati-ve** [Automattic/wp-calypso#19495]
#### Steps to reproduce
cd wp-calypso
npm start

#### fails with error
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wp-calypso@0.17.0~prestart: wp-calypso@0.17.0
6 verbose lifecycle wp-calypso@0.17.0~prestart: unsafe-perm in lifecycle true
8 verbose lifecycle wp-calypso@0.17.0~prestart: CWD: /www/wp-calypso
9 silly lifecycle wp-calypso@0.17.0~prestart: Args: [ '-c',
9 silly lifecycle   'npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )' ]
10 silly lifecycle wp-calypso@0.17.0~prestart: Returned: code: 1  signal: null
11 info lifecycle wp-calypso@0.17.0~prestart: Failed to exec prestart script
12 verbose stack Error: wp-calypso@0.17.0 prestart: `npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at EventEmitter.emit (events.js:214:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid wp-calypso@0.17.0
14 verbose cwd /www/wp-calypso
15 verbose Darwin 16.6.0
16 verbose argv "/usr/local/Cellar/node/8.9.0/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v8.9.0
18 verbose npm  v5.5.1
19 error code ELIFECYCLE
20 error errno 1
21 error wp-calypso@0.17.0 prestart: `npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )`
21 error Exit status 1
22 error Failed at the wp-calypso@0.17.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```
#### Environment
Mac OS Sierra
Node v8.9.0
NPM v5.5.1

**Comment by negati-ve** [comment]
Downgrading to node v6.11.6 solved the problem, 
(as mentioned in packages.json 
```
"engines": {
    "node": "6.11.5",
    "npm": "3.10.10"
  }
```
)
