### ISSUE TITLE
wp-calypso must run in gcc > 4.4.9 environment?

### ISSUE THREAD

**Issue by shangdev** [Automattic/wp-calypso#21817]
when i install wp-calypso, it's show a lots error info:
`
[root@webtest wp-calypso]# npm start

> wp-calypso@0.17.0 prestart /home/wwwroot/trueniu-php/wp-calypso
> npm run -s install-if-deps-outdated && node bin/welcome.js && ( check-node-version --package || exit 0 )
node: 6.11.2
npm: 3.10.10
yarn: not installed

> wp-calypso@0.17.0 start /home/wwwroot/trueniu-php/wp-calypso
> npm run -s build

fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
module.js:471
    throw err;
    ^

Error: Cannot find module 'hard-source-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/webpack.config.node.js:8:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 2.6.32-642.el6.x86_64
npm ERR! argv "/www/server/nvm/v6.11.2/bin/node" "/www/server/nvm/v6.11.2/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-calypso@0.17.0 start script 'npm run -s build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wp-calypso package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run -s build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wp-calypso
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wp-calypso
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wwwroot/trueniu-php/wp-calypso/npm-debug.log
`

We can be found from a npm package installation, it's **hard-source-webpack-plugin.**

When I installed **hard-source-webpack-plugin** separately，the following error occurred again:
`
  CXX(target) Release/obj.target/leveldown/src/batch.o
在包含自 ../src/batch.cc：3 的文件中:
../node_modules/nan/nan.h:45:3: 错误：#error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.11.2/include/node/node.h:42,
                 from ../src/batch.cc:1:
`
He prompted me gcc version is too small.

So wp gcc version of the request?

**Comment by designsimply** [comment]
I noticed these lines:

> npm ERR! node v6.11.2
> npm ERR! npm v3.10.10

and:

> npm ERR! Make sure you have the latest version of node.js and npm installed.

According to https://nodejs.org/en/download/ the latest version of node is 8.9.4 right now. Can you upgrade node to 8.9.4 and try again? I am not sure what version of gcc is required exactly (tho I tried searching Google!), but perhaps can you try updating to the latest gcc that you can?

**Comment by shangdev** [comment]
I upgrade node to v8.9.4 and npm v5.6.0.
and get the new error:
`
node: 8.9.4
npm: 5.6.0
yarn: not installed

> wp-calypso@0.17.0 start /home/wwwroot/trueniu-php/wp-calypso
> npm run -s build

fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:124:13)
    at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-calypso@0.17.0 start: `npm run -s build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-calypso@0.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-26T02_44_23_859Z-debug.log
`

**Comment by shangdev** [comment]
@designsimply 
I upgrade node to v8.9.4 and npm v5.6.0.
and get the new error:
`
node: 8.9.4
npm: 5.6.0
yarn: not installed

wp-calypso@0.17.0 start /home/wwwroot/trueniu-php/wp-calypso
npm run -s build

fs.js:904
return binding.readdir(pathModule._makeLong(path), options.encoding);
^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
at Object.fs.readdirSync (fs.js:904:18)
at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:124:13)
at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
at module.exports (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/binding.js:15:30)
at Object. (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
fs.js:904
return binding.readdir(pathModule._makeLong(path), options.encoding);
^

Error: ENOENT: no such file or directory, scandir '/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/vendor'
at Object.fs.readdirSync (fs.js:904:18)
at Object.getInstalledBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/extensions.js:124:13)
at foundBinariesList (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/errors.js:45:5)
at module.exports (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/binding.js:15:30)
at Object. (/home/wwwroot/trueniu-php/wp-calypso/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-calypso@0.17.0 start: npm run -s build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wp-calypso@0.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-01-26T02_44_23_859Z-debug.log
`

**However, there is no supplier directory for this node**

**Comment by shangdev** [comment]
OK,i have solved the qustion.
need gcc>4.4.7.
