### ISSUE TITLE
Gutenberg: Add new category link causes editor error

### ISSUE THREAD

**Issue by bsessions85** [Automattic/wp-calypso#28204]
#### Steps to reproduce
1. Starting at URL:https://wpcalypso.wordpress.com/gutenberg
2. Choose a blog
3. Click "Add a Category" in the document settings bar

#### What I expected
I expected to be able to add a new category

#### What happened instead
I see this:
![image](https://user-images.githubusercontent.com/31110506/47815781-ef620e80-dd16-11e8-9ed8-68c6e769ff3d.png)

Recovery doesn't work and the error message I can copy is:

```
TypeError: Cannot read property 'length' of null
    at t.value (https://wpcalypso.wordpress.com/calypso/vendors~async-load-gutenberg-blocks~gutenberg-editor.b877787ec6dbfc28dcad.min.js:1:405788)
    at cb (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:59761)
    at zb (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:59556)
    at db (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:63369)
    at Ib (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:77720)
    at Ub (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:78094)
    at Xr (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:84180)
    at jr (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:83719)
    at xr (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:91241)
    at jt (https://wpcalypso.wordpress.com/calypso/vendors~build.fe7128f14bb2403405db.min.js:79:30610)
```

#### Browser / OS version
Chrome 70.0.3538.77 macOS 10.14

**Comment by gwwar** [comment]
Probably related to the 4.1 upgrade. cc @vindl if you already started to look. pretty sure we need to update API middleware, wpcom should have examples.

**Comment by gwwar** [comment]
Are we a little too strict in our public.api implementation @mdawaffe? I can certainly filter this out on the client, but I think Gutenberg is making this call directly.

![screen shot 2018-11-02 at 4 52 21 pm](https://user-images.githubusercontent.com/1270189/47945508-badd8680-debf-11e8-932d-102ea3965eba.png)

![screen shot 2018-11-02 at 4 51 42 pm](https://user-images.githubusercontent.com/1270189/47945504-b1ecb500-debf-11e8-925a-157395a13db0.png)

**Comment by gwwar** [comment]
From a Jetpack site that should be per_page=100, let me see if something is off

![screen shot 2018-11-02 at 5 00 36 pm](https://user-images.githubusercontent.com/1270189/47945702-f167d100-dec0-11e8-8214-3a1dd118d582.png)

**Comment by gwwar** [comment]
Oh fun! I guess breaking chains has consequences 👍 Going to pull this in for our use.

https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/fetch-all-middleware.js
```jsx
// The REST API enforces an upper limit on the per_page option. To handle large
// collections, apiFetch consumers can pass `per_page=-1`; this middleware will
// then recursively assemble a full response array from all available pages.
const fetchAllMiddleware = async ( options, next ) => {
	if ( options.parse === false ) {
		// If a consumer has opted out of parsing, do not apply middleware.
		return next( options );
	}
	if ( ! requestContainsUnboundedQuery( options ) ) {
		// If neither url nor path is requesting all items, do not apply middleware.
		return next( options );
	}

	// Retrieve requested page of results.
	const response = await next( {
		...modifyQuery( options, {
			per_page: 100,
		} ),
		// Ensure headers are returned for page 1.
		parse: false,
	} );

	const results = await parseResponse( response );

	if ( ! Array.isArray( results ) ) {
		// We have no reliable way of merging non-array results.
		return results;
	}

	let nextPage = getNextPageUrl( response );

	if ( ! nextPage ) {
		// There are no further pages to request.
		return results;
	}

	// Iteratively fetch all remaining pages until no "next" header is found.
	let mergedResults = [].concat( results );
	while ( nextPage ) {
		const nextResponse = await next( {
			...options,
			// Ensure the URL for the next page is used instead of any provided path.
			path: undefined,
			url: nextPage,
			// Ensure we still get headers so we can identify the next page.
			parse: false,
		} );
		const nextResults = await parseResponse( nextResponse );
		mergedResults = mergedResults.concat( nextResults );
		nextPage = getNextPageUrl( nextResponse );
	}
	return mergedResults;
};

export default fetchAllMiddleware;
```
