### ISSUE TITLE
Reader: Recommendations: Console error: iterable.length has been deprecated, use iterable.size or iterable.count().

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#3493]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/recommendations
2. View the console

#### What I expected

No errors/warnings

#### What happened instead

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at OrderedSet.Object.defineProperty.get (https://wordpress.com/calypso/build-stage.f4ff76ac951d0b022036.min.js:8:22041)
    at receiveRecommendations (https://wordpress.com/calypso/reader.01a178ddf716600d270c.min.js:9:16760)
    at Object.ID_26 (https://wordpress.com/calypso/reader.01a178ddf716600d270c.min.js:9:17090)
    at Dispatcher._invokeCallback (https://wordpress.com/calypso/build-stage.f4ff76ac951d0b022036.min.js:40:10129)
    at Dispatcher.dispatch (https://wordpress.com/calypso/build-stage.f4ff76ac951d0b022036.min.js:40:9876)
    at Dispatcher.handleServerAction (https://wordpress.com/calypso/build-stage.f4ff76ac951d0b022036.min.js:2:10112)
    at https://wordpress.com/calypso/reader.01a178ddf716600d270c.min.js:12:12330
    at https://wordpress.com/calypso/reader.01a178ddf716600d270c.min.js:6:31293
    at https://wordpress.com/calypso/vendor.f4ff76ac951d0b022036.min.js:8:27316
    at XMLHttpRequest.onload (https://wordpress.com/calypso/build-stage.f4ff76ac951d0b022036.min.js:21:13660)
```

#### Browser / OS version

Chrome OSX 10.11.3

**Comment by alisterscott** [comment]
Retested all good, thanks.
