### ISSUE TITLE
Bug: Error when ~/.babelrc is present

### ISSUE THREAD

**Issue by BrianDGLS** [Automattic/wp-calypso#3803]
**URL:**
NA

**What I expected:**
I expected to run `make run` in the root directory of calypso and have that then install and build the dependencies.

**What happened instead:**
Instead I received the following error, (see screenshot for full error):

```
ERROR in ./index.js
Module build failed: ReferenceError: [BABEL] /Users/brian/Sites/wp-calypso/index.js: Unknown option: /Users/brian/.babelrc.presets
    at Logger.error (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/options/option-manager.js:124:29)
    at OptionManager.addConfig (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/options/option-manager.js:105:10)
    at OptionManager.findConfigs (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/options/option-manager.js:166:35)
    at OptionManager.init (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:10)
    at File.initOptions (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/index.js:150:75)
    at new File (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/brian/Sites/wp-calypso/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/brian/Sites/wp-calypso/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/brian/Sites/wp-calypso/node_modules/babel-loader/index.js:69:12)
```

**Steps to reproduce:**
Create a `.babelrc` file in your user directory:
`cd ~ && touch .babelrc`

Once created add the following to the `.babelrc` file:

```javascript
{
    "presets": [
        "es2015"
    ]
}
```

Now clone calypso and run `make run`.

_Note_
My Node version `v5.5.0`

**Browser OS version:**
OSX 10.11.3

**Screenshots/Video:**

![screen shot 2016-03-06 at 17 39 47](https://cloud.githubusercontent.com/assets/7824734/13555902/5ea1bcb8-e3c4-11e5-96cf-80b90fa08870.png)

**Comment by lancewillett** [comment]
Hi there — is this still happening? I'm not sure it's repeatable unless someone has that babel directory already created. Is that common, expected?
