### ISSUE TITLE
Build Error in WP-Desktop

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/wp-calypso#39323]
### Description

We recently had a brief outage of the wp-desktop canary CI job. The canary pipeline has been fixed, but it seems a Desktop build error crept into Calypso during the outage period.

This seems to be occurring in CI consistently and was introduced somewhere between SHA 45b915a (last known good SHA) and 2ad7760 (first known failing SHA). I have not been able to reproduce this locally, and it's unclear whether this is occurring on Linux only, or Mac as well.

```
// ...
lerna success - wpcom
Rendering Complete, saving .css file...
Rendering Complete, saving .css file...
Wrote CSS to /home/circleci/wp-desktop/calypso/public/editor.css
Wrote CSS to /home/circleci/wp-desktop/calypso/public/directly.css
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)

// ...
```

Refs:

https://circleci.com/gh/Automattic/wp-desktop/53426

Update:

I first noticed this in #39311 ([link](https://circleci.com/gh/Automattic/wp-desktop/53403)), but the `ci/desktop`  job passed on a subsequent build after rebase. Not sure if this is a race condition of some sort, or a subsequent commit to master corrected this issue.

**Comment by nsakaimbo** [comment]
Update: Subsequent Calypso SHA built in wp-desktop, odd:

https://circleci.com/gh/Automattic/wp-desktop/53438

Will close this issue for now and continue to monitor, will re-open if observed again.
