### ISSUE TITLE
CI: JS linting job will fail when there are a large number of JS files to lint

### ISSUE THREAD

**Issue by saramarcondes** [Automattic/wp-calypso#43631]
#### Steps to reproduce

1. Open a PR with a large number of JS files changed
2. Verify locally that linting passes correctly

#### What I expected
The lint job in Circle CI should pass

#### What happened instead
The lint job in Circle CI fails without feedback. If you run the job locally, you get this error:

```
 FILES_TO_LINT=$(
  git diff --name-only --diff-filter=d origin/master... \
    | grep -E '^(client/|server/|packages/)'            \
    | grep -E '\.[jt]sx?$'
) || exit 0

if [[ ! -z $FILES_TO_LINT ]]; then
  ./node_modules/.bin/eslint                                \
    --format junit                                          \
    --output-file "$CIRCLE_TEST_REPORTS/eslint/results.xml" \
    $FILES_TO_LINT
fi

Oops! Something went wrong! :(

ESLint: 7.1.0

Error: ENAMETOOLONG: name too long, stat '/Users/sara/projects/wp-calypso/client/blocks/reader-author-link/index.jsx
client/blocks/reader-combined-card/post.jsx
client/blocks/reader-feed-header/index.jsx
client/blocks/reader-post-card/byline.jsx
client/components/domains/register-domain-step/utility.js
client/extensions/wp-super-cache/components/advanced/accepted-filenames.jsx
client/jetpack-connect/authorize.js
client/jetpack-connect/connection-notice-types.js
client/jetpack-connect/constants.js
client/jetpack-connect/controller.js
client/jetpack-connect/jetpack-connect-notices.jsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/lib/analytics/sem.js
client/lib/analytics/track-affiliate-referral.js
client/lib/analytics/utils/index.js
client/lib/analytics/utils/is-ad-tracking-allowed.js
client/lib/analytics/utils/is-url-excluded-for-performance.js
client/lib/cart-values/index.js
client/lib/cart/actions.js
client/lib/domains/constants.js
client/lib/domains/get-tld.js
client/lib/domains/registration/availability-messages.js
client/lib/domains/registration/test/availability-messages.js
client/lib/i18n-utils/empathy-mode.js
client/lib/plugins/test/sanitize-section-content.js
client/lib/plugins/test/utils.js
client/lib/plugins/utils.js
client/lib/post-normalizer/rule-content-detect-media.js
client/lib/post-normalizer/rule-content-make-embeds-safe.js
client/lib/post-normalizer/rule-content-remove-styles.js
client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/utils/iframe-is-allowed.js
client/lib/post-normalizer/utils/index.js
client/lib/products-values/index.js
client/lib/safe-image-url/index.js
client/lib/safe-image-url/test/index.js
client/login/ssr.js
client/my-sites/comments/comment/comment-author-more-info.jsx
client/my-sites/current-site/domain-warnings.jsx
client/my-sites/domains/components/domain-warnings/index.jsx
client/my-sites/domains/components/domain-warnings/test/index.js
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/domain-management/name-servers/index.jsx
client/my-sites/marketing/connections/service-examples.jsx
client/my-sites/marketing/connections/service-tip.jsx
client/my-sites/plans/current-plan/index.jsx
client/my-sites/plugins/controller.js
client/my-sites/plugins/jetpack-plugins-setup/index.jsx
client/my-sites/site-settings/disconnect-site/confirm.jsx
client/my-sites/site-settings/form-discussion.jsx
client/my-sites/site-settings/protect.jsx
client/my-sites/themes/themes-magic-search-card/taxonomies-config.js
client/my-sites/themes/themes-magic-search-card/welcome.jsx
client/reader/get-helpers.js
client/reader/lib/author-name-filter/index.ts
client/reader/lib/site-description-filter/index.js
client/reader/lib/site-description-filter/test/index.js
client/reader/stats.js
client/server/pages/index.js
client/server/sanitize/index.js
client/state/happychat/test/middleware-calypso.js
client/state/jetpack-connect/selectors/index.js
client/state/jetpack-connect/selectors/is-site-blocked-error.js
client/state/jetpack-connect/test/selectors.js
client/state/jetpack/settings/utils.js
client/state/logstash/actions.ts
client/state/nps-survey/selectors.js
client/state/plugins/premium/selectors.js
client/state/plugins/premium/test/selectors.js
client/state/posts/actions/start-editing-post-copy.js
client/state/selectors/is-authors-email-blocked.js
client/state/selectors/test/is-authors-email-blocked.js
client/state/ui/guided-tours/selectors/index.js
packages/domain-picker/src/domain-picker/index.tsx
packages/i18n-calypso-cli/test/i18n.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.domain.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.me.connected-application.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.me.settings.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.me.settings.password.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.me.settings.profile-links.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.site.settings.js
packages/wpcom.js/test-allow-deny-lists/test.wpcom.site.wordads.js'
    at Object.statSync (fs.js:1009:3)
    at statSafeSync (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/cli-engine/file-enumerator.js:117:19)
    at FileEnumerator._iterateFiles (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/cli-engine/file-enumerator.js:331:22)
    at FileEnumerator.iterateFiles (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/cli-engine/file-enumerator.js:287:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/cli-engine/cli-engine.js:751:48)
    at ESLint.lintFiles (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/eslint/eslint.js:515:23)
    at Object.execute (/Users/sara/projects/wp-calypso/node_modules/eslint/lib/cli.js:294:36)
    at main (/Users/sara/projects/wp-calypso/node_modules/eslint/bin/eslint.js:142:52)
    at Object.<anonymous> (/Users/sara/projects/wp-calypso/node_modules/eslint/bin/eslint.js:146:2)
```

#### Context / Source

Found working on this PR https://github.com/Automattic/wp-calypso/pull/43348

**Comment by saramarcondes** [comment]
Sorry, I was mistaken about this, it only fails this way locally but in CI I missed the reporting tab.
