### ISSUE TITLE
Editor: Adding an invalid Twitter URL (username) in AT'd Site with Gutenberg crashes the editor

### ISSUE THREAD

**Issue by CompChris** [Automattic/wp-calypso#46879]
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/pages/
2. Add new page
3. Add Twitter block
4. Use invalid twitter URL, for instance https://twitter.com/thisdoesnotexistreally
5. Click Embed

#### What I expected

Editor should throw error at user when trying this

#### What happened instead

"The editor has encountered an unexpected error"

Stack Trace:

TypeError: Cannot read property 'removeChild' of null
    at a.value (https://attempt.blog/wp-content/plugins/amp/assets/js/amp-block-editor.js?ver=b3b13ff8a758a8521f20837af7d556e3:17:1897)
    at mj (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:125:147)
    at Ch (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:129:106)
    at Dh (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:133:20)
    at Aj (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:158:298)
    at unstable_runWithPriority (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
    at Da (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:280)
    at ab (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:154:190)
    at Te (https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:355)
    at https://attempt.blog/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68

#### Browser / OS version

Chromium Edge:  86.0.622.38

#### Screenshot / Video

https://d.pr/v/pbtnDr/FILXrgE16P

#### Context / Source

Slack discussion C015AL3QL7M/p1603902697016200

**Comment by tjcafferkey** [comment]
I am unable to replicate this bug. Instead I get "Sorry, this content could not be embedded." and the editor does not crash.

![Screenshot 2021-01-19 at 10 51 17](https://user-images.githubusercontent.com/8639742/105024662-43ff1a80-5a44-11eb-82b9-5aff5d16f9e2.png)

Am I doing something wrong or has this been fixed?

**Comment by apeatling** [comment]
WFM
