### ISSUE TITLE
Unexpected error in the editor: "TypeError: r is not a function"

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-calypso#47433]
This seems to be an issue with the Guteberg plugin on Atomic sites. Reporting it here instead of the main repo because it doesn't seem to be a problem with core.
 
#### Steps to reproduce

I was not able to trigger the error myself on test site, but I was able to reproduce it reliably on a user site innertwineherbs.com

To trigger it, all it takes is opening a new or editing Editor instance. The content will show up initially, but in seconds the screen will be taken by the regular `"The editor has encountered an unexpected error"` screen with options to `Attempt Recovery` or `Copy Error`.

```
TypeError: r is not a function
    at https://innertwineherbs.com/wp-content/plugins/gutenberg/build/components/index.js?ver=a147b420331e5c67fdfedf5baa142934:3:26801
    at Bh (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:126:456)
    at Dj (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162:476)
    at unstable_runWithPriority (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
    at Da (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:280)
    at xb (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162:231)
    at mk.Events.current (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:236:102)
    at Ei (https://innertwineherbs.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:41:59)
```

Disabling the Gutenberg plugin fixes the issue. In my case, disabling and reenabling didn't trigger the error anymore, but the user could still see it on their end, even after clearing cache. Disabling the plugin completely fixed the issue.

#### Browser / OS version

Tested on Chrome/Mac

#### User report
#24568279-hc

**Comment by metabreakr** [comment]
Encountered in 29702217-hc

However, Gutenberg was deactivated on this site. Reactivating the plugin was the solution in this case. 

```
TypeError: r is not a function at https://c0.wp.com/c/5.7.2/wp-includes/js/dist/components.min.js:7:309054 at Bh (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:126:456) at Dj (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:162:476) at unstable_runWithPriority (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react.min.js:25:260) at Da (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:60:280) at xb (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:162:231) at mk.Events.current (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:236:102) at Ei (https://c0.wp.com/c/5.7.2/wp-includes/js/dist/vendor/react-dom.min.js:41:59)
```

Browser: https://www.whatsmybrowser.org/b/6RV1E

**Comment by aleone89** [comment]
Another report here hc-30172003 

Prior to this happening, the language settings in the site were changed. Also, a post was published via the mobile app.
