### ISSUE TITLE
Flaky test: Launch 

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#50547]
[WPCOM] Launch (desktop) @signup @parallel Launch when having multiple sites "before all" hook: Create 2 free sites as a new user for "Can start launch flow and abandon" - "before all" hook: Create 2 free sites as a new user for "Can start launch flow and abandon"

### Error messages

single site
```
TimeoutError: Timed out waiting for element with css selector of '.is-section-reader' to be present and displayed
Wait timed out after 22212ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

multiple sites
```
TimeoutError: Timed out waiting for element with css selector of '.is-section-reader' to be present and displayed
Wait timed out after 22152ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Example failures

- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59639/workflows/78c35c0e-03ec-4d2d-94d4-4612fccf1477/jobs/144905
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59646/workflows/8eeee672-a598-4154-98c6-64c4e4ac5c1c/jobs/144928
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59633/workflows/f466a437-d40d-45c3-aec8-2b4aaf18c4f7/jobs/144900
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59631/workflows/89d29061-02b4-4c7a-82f1-b76bde6e650a/jobs/144896
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59633/workflows/f466a437-d40d-45c3-aec8-2b4aaf18c4f7/jobs/144900
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59624/workflows/a2374231-f4d3-4167-9eef-303541a6c8fa/jobs/144875
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59623/workflows/5623d49b-4189-474e-ba97-d40fb7bf5ab3/jobs/144866
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59621/workflows/a03d7c90-4522-4206-a0c6-af10d4d2be9a/jobs/144861

**Comment by worldomonation** [comment]
In general, this test tends to fail during the run-up to 00:00Z, so may have something to do with the signup limits.

Usually it is the hook that fails during the site creation.

**Comment by worldomonation** [comment]
The rewrite of this test was under way in #50411, but it ran into several issues:
- signup user a/b test: registering a new user to use for the launch test (in an isolated manner) caused A/B test of the launch screen to be applied to the user. 
- behavior difference between CI and local: tests run sequentially when run locally; on CI, the test `Launch multiple sites` experienced issues running out of order.

**Comment by worldomonation** [comment]
New WIP PR is here: #50690

**Comment by worldomonation** [comment]
Blocked due to the PR being also blocked.

**Comment by worldomonation** [comment]
Closing as this test is no longer relevant (removed from repository).
