### ISSUE TITLE
Flaky test: Basic Public Post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#50546]
[WPCOM] Calypso Gutenberg Editor: Posts (mobile) Basic Public Post @canary @parallel Publish a New Post Can publish and view content - Can publish and view content

### Error message

```
TimeoutError: Timed out waiting for element with css selector of '.components-snackbar' to be present and displayed
Wait timed out after 22237ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

or

```
TimeoutError: Timed out waiting for element with css selector of '.editor-post-publish-panel__header' to be present and displayed
Wait timed out after 22181ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Example failures

- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59653/workflows/0db25c64-011f-4494-b9c9-f5ea959256c0/jobs/144933/tests#failed-test-0
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59646/workflows/8eeee672-a598-4154-98c6-64c4e4ac5c1c/jobs/144928
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59635/workflows/69476c9b-5dfb-44ee-84dd-d440f85aff2d/jobs/144894
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59622/workflows/a2826f01-e7a5-4e29-aecd-b216488b1367/jobs/144865

**Comment by worldomonation** [comment]
The issue seems to be that on mobile screensize, the last step in `can publish and view post` which is to click on the `Publish` button is failing.

**Comment by worldomonation** [comment]
Moved this item back because there are still occasional failures. See:
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59879/workflows/20ff588c-64df-4a20-b3f2-6280e70c0a11/jobs/145405/parallel-runs/2
- https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/59883/workflows/94f295d4-4c83-43c6-82a0-16255d9e66a0/jobs/145410

Appears to be occasional but realistically a canary test should not fail for any reason other than a legitimate failure.

**Comment by worldomonation** [comment]
One possible improvement of this test; move the verification of blocks being visible to its own test. 

Justification: basic post functionality should not be burdened with verifying that certain blocks are visible.
