### ISSUE TITLE
Jetpack Backup gives blank page/WSOD

### ISSUE THREAD

**Issue by retnonindya** [Automattic/wp-calypso#51966]
Hi team! Just recently (April 15, 7:21 UTC) we received a report where user sees blank page/WSOD when they accessed Jetpack Backup (My Site > Jetpack > Backup or `https://wordpress.com/backup/DOMAINNAME`). Several HEs able to replicate it.

This is the error code on console:

```
7639.aae1c9895a934172a47a.min.js:2 TypeError: u is not a function
The error may be correlated with this previous error:
TypeError: u is not a function
    at e [as onStateChange] (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:56012)
    at e.u.handleChangeWrapper (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:46881)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:47274
    at ll (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:274718)
    at Object.notify (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:47243)
    at e.u.notifyNestedSubs (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:46813)
    at j (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:48777)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:48666
    at la (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:263979)
    at ua (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:264082)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:55703
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:56166
    at je (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:40902)
    at Ze (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:41634)
    at https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:42280
    at Be (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:42304)
    at Xs (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:238705)
    at Ui (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:247562)
    at wa (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:285974)
    at vl (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:277497)
oa @ 7639.aae1c9895a934172a47a.min.js:2
7639.aae1c9895a934172a47a.min.js:2 Uncaught TypeError: u is not a function
The error may be correlated with this previous error:
TypeError: u is not a function
    at e [as onStateChange] (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:56012)
    at e.u.handleChangeWrapper (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:46881)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:47274
    at ll (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:274718)
    at Object.notify (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:47243)
    at e.u.notifyNestedSubs (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:46813)
    at j (https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:48777)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:48666
    at la (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:263979)
    at ua (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:264082)
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:55703
    at https://wordpress.com/calypso/evergreen/56851.4f127fde6c6c690c0262.min.js:1:56166
    at je (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:40902)
    at Ze (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:41634)
    at https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:42280
    at Be (https://wordpress.com/calypso/evergreen/backup.5488e92bb36e0615c3b0.min.js:1:42304)
    at Xs (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:238705)
    at Ui (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:247562)
    at wa (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:285974)
    at vl (https://wordpress.com/calypso/evergreen/7639.aae1c9895a934172a47a.min.js:2:277497)
```

### Steps to reproduce the behavior

1. Go to `https://wordpress.com/backup/DOMAINNAME` (My Site > Jetpack > Backup)
2. See blank page

#### What I expected to happen
Able to see the backup as expected

#### What actually happened
Blank page

#### Any workaround?

Yes. It's possible to access the backup and do site rewind from Jetpack > Activity.

### Context
User report and HEs able to replicate

#### Does this happen on simple or atomic sites or both?
AT

#### Is there any console output or error text?
Mentioned above

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
High. Multiple sites.

#### Reproducibility (Consistent, Intermittent) Leave empty for consistent.
Consistent

**Comment by donalirl** [comment]
Also happening in #28718778-hc

**Comment by inaikem** [comment]
Initially noticed on 3910135-HC

**Comment by scinos** [comment]
Fixed by #51968

**Comment by retnonindya** [comment]
Yay! Thank youuu! Closing this issue now.

**Comment by tyxla** [comment]
cc @mattgawarecki and @Automattic/jetpack-voyager - as per some investigation in p1618474100102000-slack-C7YPUHBB2 this seems to be caused by #46932. We'll need to address that before doing a second pass to upgrade redux.
