### ISSUE TITLE
E2E: Flaky "Can view page title as logged in user" in wp-calypso-gutenberg-page-editor-spec.js

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#52004]
This spec seems to be flaky so let's try to fix it. Seems similar to #51948, but the error is different. This is also a mobile test.

#### Failing spec details

From: https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/65499/workflows/961e59e4-99c5-4b72-b52a-edf2827cdbf2/jobs/156607

Also: https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/65671/workflows/2f3c7037-5c40-4061-b7f0-68c907a19018/jobs/156956

```
TimeoutError: Waiting for the element to become located and visible By(css selector, .type-page)
Wait timed out after 22139ms
    at /home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by noahtallen** [comment]
Dupe of #51992
