### ISSUE TITLE
E2E: Flaky "Can log into WordPress.com" in wp-plan-purchase-spec.js

### ISSUE THREAD

**Issue by noahtallen** [Automattic/wp-calypso#52003]
This spec seems to be flaky so let's try to fix it. Note: the root problem is probably the same as #52002

#### Failing spec details

From: https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/65500/workflows/e8f04b22-f382-4186-9979-08e7561b201c/jobs/156610/tests

```
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=84.0.4147.135)
    at Object.throwDecodedError (/home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/home/circleci/wp-calypso/wp-calypso/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at async /home/circleci/wp-calypso/wp-calypso/test/e2e/lib/driver-helper.js:107:25
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
