### ISSUE TITLE
E2E: Flaky Login steps - ElementNotInteractableError

### ISSUE THREAD

**Issue by lsl** [Automattic/wp-calypso#52228]
#### Failing spec details

From https://teamcity.a8c.com/viewLog.html?buildId=6126224&buildTypeId=calypso_RunCalypsoE2eMobileTests

This build had the login step failing for multiple spec's on `sendKeys` parts.

```
ElementNotInteractableError: element not interactable
  (Session info: chrome=84.0.4147.135)
    at Object.throwDecodedError (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at async /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/lib/driver-helper.js:237:5
```

**Comment by lsl** [comment]
> Resolved issue 3744: SendKeys() and Click() silently fail after link navigation [Pri-]
https://chromedriver.storage.googleapis.com/91.0.4472.19/notes.txt

Potentially related.

**Comment by worldomonation** [comment]
Closing for now as we're close to deprecating the Selenium based framework in favor of Playwright (which has been running for 4 months now).
