### ISSUE TITLE
E2E: Flaky spec report: "Pages (desktop): Public Pages: Can enter page title, content and image" in wp-calypso-gutenberg-page-editor-spec.js

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#52256]
#### Failing spec details

From: https://teamcity.a8c.com/viewLog.html?buildId=6129664&

```
The test was run 2 times in the build, 1 failure 

TimeoutError: Waiting for the element to become located and visible By(css selector, .components-textarea-control__input)
Wait timed out after 22074ms
    at /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
