### ISSUE TITLE
E2E: Flaky spec report: "Pages (desktop): Insert a payment button into a page: Can publish and view content" in wp-calypso-gutanberg-page-editor-spec.js

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#52257]
This spec seems to be flaky so let's try to fix it.

#### Failing spec details

From https://teamcity.a8c.com/viewLog.html?buildId=6129664:

```
The test was run 2 times in the build, 1 failure 

StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=84.0.4147.135)
    at Object.throwDecodedError (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/http.js:491:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:700:17)
    at async /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/lib/driver-helper.js:114:25
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
