### ISSUE TITLE
E2E: Flaky "Like post as logged out user" in wp-likes-spec.js

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#52285]
This spec seems to be flaky both in Mobile and Desktop so let's try to fix it.

#### Failing spec details

From https://teamcity.a8c.com/viewLog.html?buildId=6130744&tab=buildResultsDiv&buildTypeId=calypso_RunCalypsoE2eDesktopTests#testNameId4157685645184999963:

```
======= Failed test run #1 ==========
TimeoutError: Waiting for the element to become located and visible By(xpath, //span[@class='wpl-count-text'][.='You like this.'])
Wait timed out after 22020ms
    at /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
======= Failed test run #2 ==========
TimeoutError: Waiting for the element to become located and visible By(xpath, //span[@class='wpl-count-text'][.='You like this.'])
Wait timed out after 20003ms
    at /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by cpapazoglou** [comment]
It proves that it was a temp backend problem
p1619432916021900-slack-C1A1EKDGQ
