### ISSUE TITLE
E2E: Flaky spec report: "Calypso Gutenberg Editor: Posts (desktop): Use the Calypso Media Modal: Can insert an image in an Image block with the Media Modal"

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#52401]
File name: `wp-calypso-gutenberg-post-editor-spec.js`.

This spec seems to be flaky so let's try to fix it.

#### Failing spec details

From https://teamcity.a8c.com/viewLog.html?buildId=6144577&tab=queuedBuildOverviewTab:

```
TimeoutError: Waiting for the element to become located and visible By(css selector, .dialog__content .media-library)
Wait timed out after 22154ms
    at /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
