### ISSUE TITLE
E2E: Flaky spec report: "Calypso Gutenberg Editor: Pages (desktop): Password Protected Pages: Publish a Password Protected Page, Can log in"

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#52400]
File name: `wp-calypso-gutenberg-page-editor-spec.js`.

This spec seems to be flaky so let's try to fix it.

#### Failing spec details

From https://teamcity.a8c.com/viewLog.html?buildId=6144577&tab=queuedBuildOverviewTab:

```
TimeoutError: Waiting for the element to become located and visible By(css selector, #content)
Wait timed out after 20123ms
    at /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/selenium-webdriver/lib/webdriver.js:842:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
