### ISSUE TITLE
E2E Flaky spec report: Can see correct page title in preview in specs/specs-wpcom/wp-calypso-gutenberg-page-editor-spec.js

### ISSUE THREAD

**Issue by fullofcaffeine** [Automattic/wp-calypso#53996]
This spec seems to be flaky so let's try to fix it.

#### Failing spec details

Found out while running e2e against Gutenberg v10.9.0 (edge):
* Desktop: https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_desktop/6338500
* Mobile: https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_mobile/6338502

```
======= Failed test run #1 ==========
  TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22095ms
  Error: TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22095ms
  at Proxy.<anonymous> (lib/driver-manager.js:104:14)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Proxy.waitUntilElementLocatedAndVisible (lib/driver-helper.js:105:9)
  at async PagePreviewComponent.waitForPage (lib/async-base-container.js:63:10)
  at async PagePreviewComponent._expectInit (lib/async-base-container.js:56:3)
  at async Function.Expect (lib/async-base-container.js:30:3)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-page-editor-spec.js:83:33)
======= Failed test run #2 ==========
  TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22048ms
  Error: TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22048ms
  at Proxy.<anonymous> (lib/driver-manager.js:104:14)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Proxy.waitUntilElementLocatedAndVisible (lib/driver-helper.js:105:9)
  at async PagePreviewComponent.waitForPage (lib/async-base-container.js:63:10)
  at async PagePreviewComponent._expectInit (lib/async-base-container.js:56:3)
  at async Function.Expect (lib/async-base-container.js:30:3)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-page-editor-spec.js:83:33)
======= Failed test run #3 ==========
  TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22122ms
  Error: TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22122ms
  at Proxy.<anonymous> (lib/driver-manager.js:104:14)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Proxy.waitUntilElementLocatedAndVisible (lib/driver-helper.js:105:9)
  at async PagePreviewComponent.waitForPage (lib/async-base-container.js:63:10)
  at async PagePreviewComponent._expectInit (lib/async-base-container.js:56:3)
  at async Function.Expect (lib/async-base-container.js:30:3)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-page-editor-spec.js:83:33)
======= Failed test run #4 ==========
  TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22122ms
  Error: TimeoutError: Waiting for the element to become located and visible By(css selector, .web-preview.is-visible)
  Wait timed out after 22122ms
  at Proxy.<anonymous> (lib/driver-manager.js:104:14)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Proxy.waitUntilElementLocatedAndVisible (lib/driver-helper.js:105:9)
  at async PagePreviewComponent.waitForPage (lib/async-base-container.js:63:10)
  at async PagePreviewComponent._expectInit (lib/async-base-container.js:56:3)
  at async Function.Expect (lib/async-base-container.js:30:3)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-page-editor-spec.js:83:33)
```

**Comment by worldomonation** [comment]
No longer relevant with Selenium long gone.
