### ISSUE TITLE
Playwright: investigate flakey failure in theme switch preview spec

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#54613]
### Details

Logs:

TeamCity run: 6423889

```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".theme__sheet-screenshot"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:284:34
at Frame._wrapApiCall (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at Frame.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:283:21)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:457:60
at Page._attributeToPage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:238:20)
at Page.click (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/page.js:457:21)
at ThemesDetailPage.preview (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/themes-detail-page.ts:20:19)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-theme__switch-preview-spec.js:46:26)
at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
at new Promise (<anonymous>)
at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)
at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-config/node_modules/jest-runner/build/runTest.js:389:16)
at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-config/node_modules/jest-runner/build/runTest.js:481:34)
at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-config/node_modules/jest-runner/build/testWorker.js:133:12)
```

Playwright logs:
```
2021-07-15T15:36:03.597Z 490 api info: => browserContext.newPage started
2021-07-15T15:36:03.704Z 490 api info: <= browserContext.newPage succeeded
2021-07-15T15:36:03.705Z 490 api info: => page.goto started
2021-07-15T15:36:04.282Z 490 api info: <= page.goto succeeded
2021-07-15T15:36:04.316Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:04.343Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:04.344Z 490 api info: => page.waitForLoadState started
2021-07-15T15:36:05.152Z 490 api info: <= page.waitForLoadState succeeded
2021-07-15T15:36:05.152Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:05.159Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:05.160Z 490 api info: => elementHandle.waitForElementState started
2021-07-15T15:36:05.176Z 490 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T15:36:05.177Z 490 api info: => page.$ started
2021-07-15T15:36:05.179Z 490 api info: <= page.$ succeeded
2021-07-15T15:36:05.179Z 490 api info: => page.fill started
2021-07-15T15:36:05.193Z 490 api info: <= page.fill succeeded
2021-07-15T15:36:05.204Z 490 api info: => page.fill started
2021-07-15T15:36:05.301Z 490 api info: <= page.fill succeeded
2021-07-15T15:36:05.316Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:08.763Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:08.763Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:08.819Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:08.820Z 490 api info: => elementHandle.waitForElementState started
2021-07-15T15:36:08.865Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:08.865Z 490 api info: <= elementHandle.waitForElementState succeeded
2021-07-15T15:36:08.891Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:08.892Z 490 api info: => page.evaluate started
2021-07-15T15:36:08.901Z 490 api info: <= page.evaluate succeeded
2021-07-15T15:36:08.901Z 490 api info: => elementHandle.click started
2021-07-15T15:36:09.025Z 490 api info: <= elementHandle.click succeeded
2021-07-15T15:36:09.025Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:09.185Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:09.186Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:09.188Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:09.263Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:09.263Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:09.263Z 490 api info: => page.click started
2021-07-15T15:36:09.725Z 490 api info: <= page.click succeeded
2021-07-15T15:36:09.725Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:10.018Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:10.018Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:10.159Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:10.160Z 490 api info: => page.waitForFunction started
2021-07-15T15:36:10.205Z 490 api info: <= page.waitForFunction succeeded
2021-07-15T15:36:10.205Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:10.222Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:10.222Z 490 api info: => elementHandle.fill started
2021-07-15T15:36:10.245Z 490 api info: <= elementHandle.fill succeeded
2021-07-15T15:36:10.245Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:10.376Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:10.377Z 490 api info: => page.waitForSelector started
2021-07-15T15:36:10.404Z 490 api info: <= page.waitForSelector succeeded
2021-07-15T15:36:10.404Z 490 api info: => elementHandle.click started
2021-07-15T15:36:10.586Z 490 api info: <= elementHandle.click succeeded
2021-07-15T15:36:10.587Z 490 api info: => page.click started
2021-07-15T15:36:40.594Z 490 api info: <= page.click failed
2021-07-15T15:36:40.595Z 490 api info: => page.screenshot started
2021-07-15T15:36:40.759Z 490 api info: <= page.screenshot succeeded
2021-07-15T15:36:40.759Z 490 api info: => page.close started
2021-07-15T15:36:40.771Z 490 api info: <= page.close succeeded
```

### Checklist

- [ ]
- [ ]

**Comment by worldomonation** [comment]
Ah, this one is because the initial version of `ThemesPage.select` I wrote wasn't quite as robust as I wanted it to be.

I've pushed a revised version as part of #54048 and that's pending review. This issue should be resolved with that push.

**Comment by worldomonation** [comment]
Closing this issue.
