### ISSUE TITLE
[GB 11.1.0] E2E test wp-calypso-gutenberg-post-editor-spec.js fails

### ISSUE THREAD

**Issue by scinos** [Automattic/wp-calypso#54760]
Test suite: `[WPCOM] Calypso Gutenberg Editor: Posts (desktop): Public Posts: Preview and Publish a Public Post @parallel`
Test name: `Can enter post title, content and image `

Error:

```
  TimeoutError: Waiting for element to be settable By(css selector, input.block-editor-inserter__search-input) to "Image"
  Wait timed out after 22210ms
  Error: TimeoutError: Waiting for element to be settable By(css selector, input.block-editor-inserter__search-input) to "Image"
  Wait timed out after 22210ms
  at Proxy.<anonymous> (lib/driver-manager.js:97:14)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Proxy.setWhenSettable (lib/driver-helper.js:304:9)
  at async GutenbergEditorComponent.openBlockInserterAndSearch (lib/gutenberg/gutenberg-editor-component.js:252:3)
  at async GutenbergEditorComponent.addBlock (lib/gutenberg/gutenberg-editor-component.js:417:3)
  at async GutenbergEditorComponent.addImage (lib/gutenberg/gutenberg-editor-component.js:454:19)
  at async Context.<anonymous> (specs/specs-wpcom/wp-calypso-gutenberg-post-editor-spec.js:57:4)
```

**Comment by scinos** [comment]
Likely caused by https://github.com/WordPress/gutenberg/pull/32935
