### ISSUE TITLE
Playwright: flaky behavior on mobile GutenbergEditorPage.publish

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#54932]
### Details

Relevant log:

```
frame.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".editor-post-publish-panel a:has-text("View")" to be visible
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/utils/stackTrace.js:50:19)
at Connection.sendMessageToServer (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/connection.js:65:48)
at Proxy.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:64:61)
at /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:207:42
at Frame._wrapApiCall (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/channelOwner.js:77:34)
at Frame.waitForSelector (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright/lib/client/frame.js:202:21)
at GutenbergEditorPage.publish (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:155:55)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-likes__comment-spec.js:49:19)
```

Looking at the video, the publish panel slides in when the main `Publish` button is clicked on the editor. The final `publish` button there is clicked (or so Playwright thinks) but in reality the button was not ready to be clicked yet so the publish process hangs there.

### Checklist

Possible solutions:
- [ ] wait for element to be stable (animation done).
- [ ] wait for element to be enabled  (use the elementhelper).

Second approach may not work as the `waitForElementEnabled` method may not accept a frame instead of a page?

**Comment by worldomonation** [comment]
Addressed.
