### ISSUE TITLE
Playwright: Increase uniqueness of test filename

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#55717]
### Spec

wp-media__edit-spec.ts

### Suite

Media (Edit)

### Framework

Playwright

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "figure[title="1629841489617.jpg"]" to be visible
============================================================
at MediaPage.upload (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/media-page.ts:164:27)
at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-media__edit-spec.js:46:32)
```

**Comment by worldomonation** [comment]
The issue is due to an intermittent conflict of the filenames when test files are generated. The timestamp alone is not unique enough, so look at adding a suffix of randomly generated integer from 100-999 (like with the `getBlogName` method).

**Comment by worldomonation** [comment]
#55693 is superseding #55720.

**Comment by worldomonation** [comment]
Back to being on hold as it may not be necessary now that MediaHelper methods are running async.
