### ISSUE TITLE
Playwright: remove clearAuthenticatedState from library.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#55845]
### Details

Intermittently, the `clearAuthenticatedState` method flakes out:

```
specs/specs-playwright/wp-notifications__trash-spec.js

12:38:14     [WPCOM] Notifications: (mobile) @parallel

12:38:14       Log in as commentingUser

12:38:14       View site

12:38:14       View first post

12:38:14       Comment on the post

12:38:14       Clear cookies

12:38:14         page.goto: Timeout 30000ms exceeded.
        =========================== logs ===========================
        navigating to "p7Cmog-16-p2#comment-292018", waiting until "load"
        ============================================================

12:38:14         at Object.clearAuthenticationState (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/browser-manager.ts:135:13)
            at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js:47:3)
```

### Checklist

- [ ] Investigate behavior of the clearAuthenticatedState.
- [ ] Stress test any changes

**Comment by worldomonation** [comment]
This resurfaced in https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6657087?.

```
page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://e2eflowtestingnotifications.wordpress.com/2021/07/29/a-new-post-for-commenting-29jul21/#comment-294253", waiting until "load"
```

**Comment by worldomonation** [comment]
Another instance at https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6793917:

```
page.goto: net::ERR_ABORTED at https://container-reverent-tesla.calypso.live/log-in
=========================== logs ===========================
navigating to "https://container-reverent-tesla.calypso.live/log-in", waiting until "load"
============================================================
at LoginFlow.logIn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/login-flow.ts:71:19)
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-reader__view-spec.ts:47:19)
at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)
at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:481:34)
at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
Generally speaking, it is preferable to navigate to the LoginPage endpoint and let the `revealLoginForm` handle the user account switch instead of using this cookie method.

The cookie method should be considered a nuclear option that will have its own fallout/consequences.

**Comment by worldomonation** [comment]
Repurposing this issue to remove the method from the library instead.

**Comment by worldomonation** [comment]
On second look, it seems that this method is still used in two places in the spec files, and neither of them have caused problems so far:

- test/e2e/specs/specs-playwright/wp-invite__new-user.ts
- test/e2e/specs/specs-playwright/wp-likes__post-spec.js

In both of these cases, having this method is actually quite useful as it 1) avoids having to create a new Context for one step, and 2) the flow requires that next user account not be logged into the webapp (eg. using invite link, or triggering a popup).

@dpasque What do you think? Perhaps we can instead strongly suggest test writers not use this method in the JSDoc, or mark it as deprecated?

**Comment by worldomonation** [comment]
I'm going to close this issue for now as there are at least two specs that use this to no detrimental effect.
