### ISSUE TITLE
Flaky E2E: Reader (Notifications)

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56211]
### Spec

wp-reader__view-spec.ts

### Suite

Wait for Undo Message to display and then disappear

### Framework

Playwright

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".wpnc__undo-item" to be visible
============================================================
at NotificationsComponent.waitForUndoMessage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/notifications-component.ts:66:19)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-reader__view-spec.ts:66:32)
at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)
at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:481:34)
at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)

https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/6692217?buildTab=overview#%2Fscreenshots

It looks like the `Trash` button is never clicked, despite Playwright thinking it was clicked.
Might need to add a wait for the comment expansion pane to be fully stabilized first.

**Comment by worldomonation** [comment]
Addressed in #56241.
