### ISSUE TITLE
Flaky E2E: Log in

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56400]
### Spec

across many times

### Suite

Log In

### Framework

Playwright

### Logs

```
page.fill: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#usernameOrEmail"
  selector resolved to visible <input disabled value="" type="text" autocorrect="off" …/>
elementHandle.fill("<username>")
  waiting for element to be visible, enabled and editable
element is not enabled - waiting...
element was detached from the DOM, retrying
waiting for selector "#usernameOrEmail"
============================================================
at LoginPage.login (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/login-page.ts:77:19)
at LoginFlow.baseflow (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/login-flow.ts:46:3)
at LoginFlow.logIn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/login-flow.ts:59:3)
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-media__edit-spec.ts:38:4)
```

From what I can tell, this happens when Playwright thinks the Switch User button has been clicked, but it did not in fact occur.

Some possible mitigation methods:

- wait until the container is fully rendered on page (likely already done via `waitForElementState('stable')`).
- wait until a load state?
- bypass this method of switching users entirely (eg. clear cookie, traditional logout process)?

**Comment by worldomonation** [comment]
Example: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6724645?

**Comment by worldomonation** [comment]
Proposed solution in the works at #56482.
