### ISSUE TITLE
Widget-Visibility: null->render() leads to 500 error on Simple Sites

### ISSUE THREAD

**Issue by mreishus** [Automattic/wp-calypso#56546]
## Summary

After Automattic/jetpack#20731 is deployed, some sites crash `Call to a member function render() on null in /home/wpcom/public_html/wp-includes/class-wp-block.php:211`

## See Also

*  #56526 

### More Info

Stack trace:
```

#0 /home/wpcom/public_html/wp-includes/blocks.php(868): WP_Block->render()
#1 /home/wpcom/public_html/wp-content/mu-plugins/widget-conditions.php(794): render_block(Array)
#2 /home/wpcom/public_html/wp-content/mu-plugins/widget-conditions.php(723): Jetpack_Widget_Conditions::filter_widget(Array)
#3 /home/wpcom/public_html/wp-includes/class-wp-hook.php(303): Jetpack_Widget_Conditions::sidebars_widgets(Array)
#4 /home/wpcom/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#5 /home/wpcom/public_html/wp-includes/widgets.php(1035): apply_filters('sidebars_widget...', Array)
#6 /home/wpcom/public_html/wp-includes/widgets.php(903): wp_get_sidebars_widgets()
#7 /home/wpcom/public_html/wp-content/mu-plugins/widgets/reservations.php(145): is_active_widget(NULL, NULL, 'reservations')
#8 /home/wpcom/public_html/wp-includes/class-wp-hook.php(303): reservations_widget_style('')
#9 /home/wpcom/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#10 /home/wpcom/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#11 /home/wpcom/public_html/wp-includes/script-loader.php(2083): do_action('wp_enqueue_scri...')
#12 /home/wpcom/public_html/wp-includes/class-wp-hook.php(303): wp_enqueue_scripts('')
#13 /home/wpcom/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#14 /home/wpcom/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#15 /home/wpcom/public_html/wp-includes/general-template.php(3015): do_action('wp_head')
#16 /home/wpcom/public_html/wp-content/themes/pub/twentysixteen/header.php(21): wp_head()
#17 /home/wpcom/public_html/wp-includes/template.php(770): require_once('/home/wpcom/pub...')
#18 /home/wpcom/public_html/wp-includes/template.php(716): load_template('/home/wpcom/pub...', true, Array)
#19 /home/wpcom/public_html/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#20 /home/wpcom/public_html/wp-content/themes/pub/twentysixteen/page.php(14): get_header()
#21 /home/wpcom/public_html/wp-includes/template-loader.php(106): include('/home/wpcom/pub...')
#22 /home/wpcom/public_html/wp-blog-header.php(19): require_once('/home/wpcom/pub...')
#23 /home/wpcom/public_html/index.php(17): require('/home/wpcom/pub...')
#24 {main}
  thrown in /home/wpcom/public_html/wp-includes/class-wp-block.php on line 211 
```

**Comment by mreishus** [comment]
Here's a logstash link for this one: 2a502-pb/
I have been unable to reproduce this. For #56526, I reverted the revert of widget visibility on my sandbox without committing: (`svn merge --ignore-ancestry -c -232237 .`), then edited my hosts file to point a known crashing site to my sandbox, then loaded that site.
On the logstash link, I only see one site throwing the error, and when I replicate the same instructions on this site, it doesn't error.
Looking at the logs, all of the errors seem to involve  to the "jetpack top posts" widget or the "reversations" widget. I have been playing around with these on my test site and haven't gotten it to crash yet.

**Comment by mreishus** [comment]
Created https://github.com/Automattic/jetpack/pull/21222

**Comment by mreishus** [comment]
We've launched widget visibility, reworked a bit, so this error can no longer occur. Please re-open if you are seeing any other issues like this.
