### ISSUE TITLE
Start: purchase on domain-only flow takes long time to complete

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56716]
### Steps to reproduce

prereq. set store sandbox cookie.

1. start at `/start/domain`.
2. search for a domain.
3. select a .live domain.
4. select `Buy just the domain`.
5. create an account.
6. checkout with a Stripe test card. 

### What you expected to happen

The checkout should complete within a reasonable amount of time.

### What actually happened

The checkout process takes upwards of 30-45 seconds when run locally in browser, and more than 60 seconds when run in CI.

![close-account-2021-09-30T21-56-57](https://user-images.githubusercontent.com/6549265/135537779-10c94523-171c-4149-a9fa-861547e025b8.png)

https://user-images.githubusercontent.com/6549265/135537669-5aa71cc5-e015-45a4-9a12-c969bfeffa6a.mp4

)

### Context

Playwright automated tests

### Other notes

```
waitForNavigation: Timeout 30000ms exceeded.
          =========================== logs ===========================
          waiting for navigation to "**/checkout/thank-you/no-site/**" until "networkidle"
          ============================================================

14:56:58           at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__domain.ts:89:10)
              at Promise.then.completed (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
              at callAsyncCircusFn (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
              at _callCircusTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
              at _runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
              at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
              at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
              at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
              at run (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
              at runAndTransformResultsToJestFormat (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:166:21)
              at jestAdapter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
              at runTestInternal (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
              at runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:481:34)
              at Object.worker (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

```
      page.waitForNavigation: Timeout 30000ms exceeded.

14:56:58       =========================== logs ===========================

14:56:58       waiting for navigation to "**/checkout/thank-you/no-site/**" until "networkidle"

14:56:58       ============================================================

14:56:58   

14:56:58         87 |       // See: https://github.com/Automattic/wp-calypso/issues/56548

14:56:58         88 |       await Promise.all( [

14:56:58       > 89 |         page.waitForNavigation( {

14:56:58            |              ^

14:56:58         90 |           url: '**/checkout/thank-you/no-site/**',

14:56:58         91 |           waitUntil: 'networkidle',

14:56:58         92 |         } ),

14:56:58   

14:56:58         at Object.<anonymous> (specs/specs-playwright/wp-signup__domain.ts:89:10)
```

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Likely can refresh the checkout page and retry.

**Comment by jordesign** [comment]
Have added this for further triage - will need someone with Sandbox access to test fully and see if this is still relevant.

**Comment by Robertght** [comment]
Asking here: p1740138206992709-slack-C07H21B2W59

**Comment by Robertght** [comment]
I tested this following @dsas's suggestion [here](p1740138206992709-slack-C07H21B2W59) and tested this on my end. The checkout completed in ~5 seconds after pressing that button.

I'm going to close this for one and mark it as "Not reproducible".
