### ISSUE TITLE
Flaky E2E: Commenting on notification post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#56770]
### Spec file

wp-notifications__trash-spec.js

### Suite or step

Comment on the post

### Framework

Playwright

### Logs

```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
  navigated to "p7Cmog-1b-p2#comment-304387"
  "domcontentloaded" event fired
  "networkidle" event fired
  "domcontentloaded" event fired
  "domcontentloaded" event fired
  "networkidle" event fired
============================================================
at CommentsComponent.postComment (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/comments-component.ts:50:14)
at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-notifications__trash-spec.js:49:4)
```

**Comment by worldomonation** [comment]
No longer relevant as this part of the spec is refactored.
