### ISSUE TITLE
Tiled Gallery Block: The editor has encountered an unexpected error on Mosaic style

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/wp-calypso#56922]
### Quick summary

Switching the Tiled Gallery block to Mosaic and saving causes the editor to show The editor has encountered an unexpected error when you try to edit the page the next time. 

### Steps to reproduce

1. Start at Pages → Add New
2. On a blank page, add the tiled gallery block and add some images (in my test I added 10), switch the block style to Columns
3. Publish the page
4. Edit the page again, and switch the style to mosaic - note in the preview the style doesn't change
5. Publish the page - note in the live site the style doesn't change
6. Exit the Editor and try to edit the page again

### What you expected to happen

The page should be editable, and the tiled gallery block on the live site should be in the Mosiac style. 

### What actually happened

The error "The editor has encountered an unexpected error." appears and the page cannot be recovered. Error text from the "Copy Error" button:

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://s0.wp.com/_static/??-eJydUu1ugzAMfKGFjCKx/pn2KFM+vNSUfCxxSnn7uaxUU1cxaT+QyeG73NnIKQkTA0EgmcbqMBTpKh81ZCemZKK/Pwu1N81QnuQm1cQM8tS2Td88S11xtFKFEEkRRm7EYOHceAz3Sr6KVWwASsoc5TsGI/UYzbFIsEgxCw2kHrFXapkDqfMB3WHkhyBLi4WuIs1i518RMihDAtt9+J2AXY7VAvvm+9NjfPiskOdraX52rTYuZBjB0G6tj3Iqy+BtULwUXwPSLEg5x2Hvgb/oaRYp8nxubxtbmdA6IN7EiT/ojAQXz9+oWIQ3yOqIxXNfxxNd1noFNijlEDOZaEGA12D54qVsR5oSK3wAWM0/ELe++de277p+97LruuELHu0ZAg==:107:570730
    at Array.map (<anonymous>)
    at https://s0.wp.com/_static/??-eJydUu1ugzAMfKGFjCKx/pn2KFM+vNSUfCxxSnn7uaxUU1cxaT+QyeG73NnIKQkTA0EgmcbqMBTpKh81ZCemZKK/Pwu1N81QnuQm1cQM8tS2Td88S11xtFKFEEkRRm7EYOHceAz3Sr6KVWwASsoc5TsGI/UYzbFIsEgxCw2kHrFXapkDqfMB3WHkhyBLi4WuIs1i518RMihDAtt9+J2AXY7VAvvm+9NjfPiskOdraX52rTYuZBjB0G6tj3Iqy+BtULwUXwPSLEg5x2Hvgb/oaRYp8nxubxtbmdA6IN7EiT/ojAQXz9+oWIQ3yOqIxXNfxxNd1noFNijlEDOZaEGA12D54qVsR5oSK3wAWM0/ELe++de277p+97LruuELHu0ZAg==:107:570639
    at Array.map (<anonymous>)
    at d.render (https://s0.wp.com/_static/??-eJydUu1ugzAMfKGFjCKx/pn2KFM+vNSUfCxxSnn7uaxUU1cxaT+QyeG73NnIKQkTA0EgmcbqMBTpKh81ZCemZKK/Pwu1N81QnuQm1cQM8tS2Td88S11xtFKFEEkRRm7EYOHceAz3Sr6KVWwASsoc5TsGI/UYzbFIsEgxCw2kHrFXapkDqfMB3WHkhyBLi4WuIs1i518RMihDAtt9+J2AXY7VAvvm+9NjfPiskOdraX52rTYuZBjB0G6tj3Iqy+BtULwUXwPSLEg5x2Hvgb/oaRYp8nxubxtbmdA6IN7EiT/ojAQXz9+oWIQ3yOqIxXNfxxNd1noFNijlEDOZaEGA12D54qVsR5oSK3wAWM0/ELe++de277p+97LruuELHu0ZAg==:107:570593)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.6.0/build/element/index.min.js?m=1630518223h&ver=51b038d0a9e09d863ec01732ed923941:1:6898
    at j (https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.6.0/build/element/index.min.js?m=1630518223h&ver=51b038d0a9e09d863ec01732ed923941:1:6912)
    at A (https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.6.0/build/element/index.min.js?m=1630518223h&ver=51b038d0a9e09d863ec01732ed923941:1:7905)
    at N (https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.6.0/build/element/index.min.js?m=1630518223h&ver=51b038d0a9e09d863ec01732ed923941:1:7373)
    at j (https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.6.0/build/element/index.min.js?m=1630518223h&ver=51b038d0a9e09d863ec01732ed923941:1:6689)
```

### Context

Initially a customer report in #32115679-hc and I was able to reproduce on my own test site. The customer's content was recovered by going to an earlier revision of the page through the Classic Editor since the Block Editor would not load. ,

### Simple, Atomic or both?

Simple, Atomic

### Other notes

The issue did not happen when switching to the Circles style.

### Reproducibility

Consistent

**Comment by Greatdane** [comment]
Can reproduce. Error log;

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://[testsite].wpcomstaging.com/wp-content/plugins/jetpack/_inc/blocks/editor-experimental.min.js?ver=10.3-2110.1:24:558743
    at Array.map (<anonymous>)
    at https://[testsite].wpcomstaging.com/wp-content/plugins/jetpack/_inc/blocks/editor-experimental.min.js?ver=10.3-2110.1:24:558652
    at Array.map (<anonymous>)
    at d.render (https://[testsite].wpcomstaging.com/wp-content/plugins/jetpack/_inc/blocks/editor-experimental.min.js?ver=10.3-2110.1:24:558606)
    at https://[testsite].wpcomstaging.com/wp-content/plugins/gutenberg/build/element/index.min.js?ver=51b038d0a9e09d863ec01732ed923941:1:6898
    at j (https://[testsite].wpcomstaging.com/wp-content/plugins/gutenberg/build/element/index.min.js?ver=51b038d0a9e09d863ec01732ed923941:1:6912)
    at A (https://[testsite].wpcomstaging.com/wp-content/plugins/gutenberg/build/element/index.min.js?ver=51b038d0a9e09d863ec01732ed923941:1:7905)
    at N (https://[testsite].wpcomstaging.com/wp-content/plugins/gutenberg/build/element/index.min.js?ver=51b038d0a9e09d863ec01732ed923941:1:7373)
    at j (https://[testsite].wpcomstaging.com/wp-content/plugins/gutenberg/build/element/index.min.js?ver=51b038d0a9e09d863ec01732ed923941:1:6689)
```

**Comment by dpasque** [comment]
Tagging @Automattic/flow-patrol-create based on issue content

**Comment by goblinartificer** [comment]
Similar issue in 5059572-hc ⁠— the page is editable, but adding any images to it causes the error then. 

Two more points of difference: 

- Weird jitter on changing block style: https://d.pr/v/8rbmoj (similar to Automattic/jetpack#11783 maybe)
- Changing style did not fix the error, so it's not just Mosaic

Error log: 

```
Pa@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:36484
Me@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:12897
Me@[native code]
https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2Ni/NifJZ+kMlWy0Lppm9v9ebR9AgkvwD5m31VgbJAFrOmOmEuZqqt9MBTmzCYzVo9amt8xRTNAi9PjqMqd2IJVYrBHOGpH5j1XA7mXzCTYIBeRWiBrBIW6YR24hio5l7HJwqLgohC3El9Wio6cZ0OQy3OJ1Df3Xo/XoA3YFUwgmJoVO+ZG8K+tkz9MLfH1Z5Pgx3G43CZ3x3H96I=:69:6978
Tj@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:2434
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3610
gf@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2016
gf@[native code]
https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12525
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3610
$g@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12472
ja@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12407
Pa@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:36636
Me@https://s0.wp.com/wp-content/plugins/gutenberg-core/v11.7.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:12897
Me@[native code]
e@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:19842
t@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:19909
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:14313
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:13435
y@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:6847
https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2Ni/NifJZ+kMlWy0Lppm9v9ebR9AgkvwD5m31VgbJAFrOmOmEuZqqt9MBTmzCYzVo9amt8xRTNAi9PjqMqd2IJVYrBHOGpH5j1XA7mXzCTYIBeRWiBrBIW6YR24hio5l7HJwqLgohC3El9Wio6cZ0OQy3OJ1Df3Xo/XoA3YFUwgmJoVO+ZG8K+tkz9MLfH1Z5Pgx3G43CZ3x3H96I=:93:10982
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:11692
https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2Ni/NifJZ+kMlWy0Lppm9v9ebR9AgkvwD5m31VgbJAFrOmOmEuZqqt9MBTmzCYzVo9amt8xRTNAi9PjqMqd2IJVYrBHOGpH5j1XA7mXzCTYIBeRWiBrBIW6YR24hio5l7HJwqLgohC3El9Wio6cZ0OQy3OJ1Df3Xo/XoA3YFUwgmJoVO+ZG8K+tkz9MLfH1Z5Pgx3G43CZ3x3H96I=:93:37655
https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2Ni/NifJZ+kMlWy0Lppm9v9ebR9AgkvwD5m31VgbJAFrOmOmEuZqqt9MBTmzCYzVo9amt8xRTNAi9PjqMqd2IJVYrBHOGpH5j1XA7mXzCTYIBeRWiBrBIW6YR24hio5l7HJwqLgohC3El9Wio6cZ0OQy3OJ1Df3Xo/XoA3YFUwgmJoVO+ZG8K+tkz9MLfH1Z5Pgx3G43CZ3x3H96I=:22:58068
forEach@[native code]
emit@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:13778
i@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:13853
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:14313
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:13435
y@https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:6847
https://s0.wp.com/_static/??-eJylkkFuwzAMBD9UmRVqNL0UfYstETYdSXRE0kl+H+Va5BLoSJAYLIYL190FLopFYU+2UBFYrI0z1qVtKsLh/XAaPMxGKQKJk3VKia8OLzYloBLxNmQqwyYf8C7ujPfAEaUTs1fiSnp3F0PDTljgvLP0UipGu7nKplR6WXHSqROxak6uXZNSt21ZuerzbZ2cOXE4vwhDJSR7lmITiCQKB5bIFTLnxu6x2Ju49Sw3g8c/hX/5139/jX48fY4/2wMK0DPj:12:11692
setAttributes@https://s0.wp.com/_static/??-eJyl0s0OwjAIB/AXsq2Ni/NifJZ+kMlWy0Lppm9v9ebR9AgkvwD5m31VgbJAFrOmOmEuZqqt9MBTmzCYzVo9amt8xRTNAi9PjqMqd2IJVYrBHOGpH5j1XA7mXzCTYIBeRWiBrBIW6YR24hio5l7HJwqLgohC3El9Wio6cZ0OQy3OJ1Df3Xo/XoA3YFUwgmJoVO+ZG8K+tkz9MLfH1Z5Pgx3G43CZ3x3H96I=:22:52406
setAttributes@https://s0.wp.com/_static/??-eJyFUu1SwyAQfCEBY7XtH8dHcQic9BK+So42eXuvH+l0tMYfDLDsLnsc6piFSZEgksq+OoyDcpW3LRTHJwXUoWnkRjaqreit0jEm0oSJiRgtjDJglN3wpO6cQhWzWQeUtenVJ0ajWp9MPyiwSKkIGDMUDCzQ/pHLbDFMzBh36HaeB0FRFge6mslzrL+ki6UU0IYENtv4uxJO66sFzs/358d4t69Qpusk71lzjJMYPBh6medHdWrL4O3BTAqhRqRJkHaOi/0J/CfPk8iJ3+e2WujOEa0D4o4c+KAtSHDKfEHF2XhBrHscAvNW8vnS3iuwHPCY2eILwLb8LZj6Ed6b9epttX7dbjfdN/6G8zQ=:25:540877
https://s0.wp.com/_static/??-eJyFUu1SwyAQfCEBY7XtH8dHcQic9BK+So42eXuvH+l0tMYfDLDsLnsc6piFSZEgksq+OoyDcpW3LRTHJwXUoWnkRjaqreit0jEm0oSJiRgtjDJglN3wpO6cQhWzWQeUtenVJ0ajWp9MPyiwSKkIGDMUDCzQ/pHLbDFMzBh36HaeB0FRFge6mslzrL+ki6UU0IYENtv4uxJO66sFzs/358d4t69Qpusk71lzjJMYPBh6medHdWrL4O3BTAqhRqRJkHaOi/0J/CfPk8iJ3+e2WujOEa0D4o4c+KAtSHDKfEHF2XhBrHscAvNW8vnS3iuwHPCY2eILwLb8LZj6Ed6b9epttX7dbjfdN/6G8zQ=:25:539518
https://widgets.wp.com/wpcom-block-editor/calypso.editor.min.js?ver=20211028062833:22:8115
```

**Comment by Gustavo-Hilario** [comment]
This very same issue also happens in the widget area. User report here: 4530554-zd-woothemes

**Comment by galakhyati** [comment]
Similar issue happening in the widget area in these two cases:

4547731-zd-woothemes
31403958-hc

**Comment by sarahcada** [comment]
Another report happening in the widget area: 32932316-hc
The block was Blog Posts block. 
The customer's content was recovered by going to an earlier revision of the page through Appearance > Widgets.

**Comment by galakhyati** [comment]
The user in #4547731-zd-woothemes shared the issue only happens on the Customizer > Widget.
When editing the widget from My Site → Appearance → Widgets it works fine.

**Comment by galakhyati** [comment]
Another case here: #4547072-zd-woothemes

**Comment by happychait** [comment]
Encountered the `Copy Error` in the Customizer, last week in 4546706-zen. The site had the Latest Posts block widget.

Here is the copied error:

```
    TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://thenewmomlife.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:144:41)
    at Qj (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:176:361)
    at unstable_runWithPriority (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
```

**Comment by happychait** [comment]
Another report in 4550914-zen

**Comment by happychait** [comment]
Another report in 32938918-hc

**Comment by happychait** [comment]
Another report in 4548849-zen

**Comment by happychait** [comment]
Another issue in #4547072-zen. On the user's site, the widgets are not even available on the WP-Admin Widgets page. which is empty, although widgets throw the TypeError in the Customizer → Widgets panel.

**Comment by alshakero** [comment]
Fix is ready in https://github.com/Automattic/jetpack/pull/21892

**Comment by sharonlaker19** [comment]
Just played into the ticket at 4547072-zen I've tested and the widgets now load without error. 
Informing the user that the fix is ready and asking them to try again.

**Comment by alshakero** [comment]
Hi @sharonlaker19! The fix isn't deployed yet.

**Comment by happychait** [comment]
Another report in 4554961-zen

**Comment by rw-ye** [comment]
Report here: 4553339-zd-woothemes

The issue is with the image block in the widgets section.  (Customizer > Widgets)

**Comment by galakhyati** [comment]
Another report in here: 24041920-hc
Follow up: 4556198-zd-woothemes

**Comment by rw-ye** [comment]
Another report: 4552863-zd-woothemes

Image block causing widgets to show an error. (Customizer > Widgets)

User would like an update when resolved. 

```
TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://thenewmomlife.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:144:41)
    at Qj (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:176:361)
    at unstable_runWithPriority (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://thenewmomlife.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
```

**Comment by rachelwinspear** [comment]
Another report: 4546009-zen

```

hv/<@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/build/block-editor/index.min.js?m=1637285849h&ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1727
Bj@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:29846
Qj@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:876
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609
Za@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302
eb@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:6341
gf@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2337
$g/<@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
unstable_runWithPriority@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609
Za@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302
$g@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12472
ja@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12405
@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:10:14674
Ki@https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:5:1411


```

**Comment by alshakero** [comment]
Some of the comments here are not exactly related to the issue here. This issue logs the error 

```
TypeError: Cannot read properties of undefined (reading '0')
```

If you're getting the following error: 
```
TypeError: Cannot read properties of null (reading 'scrollTop')
```
Please track this issue instead https://github.com/WordPress/gutenberg/issues/36999

**Comment by radtechgh** [comment]
User reported again, they are still having this issue. 4547072-zen

**Comment by alshakero** [comment]
Hi @Camaropilot! Since the user has an Atomic site, I think they'll need to wait until Jetpack's release to get the bugfix. 

Can you please confirm @jeherve?

**Comment by jeherve** [comment]
The changes were shipped to Atomic, as per p9o2xV-1Jn-p2 , so they should not see the issue anymore.

The ticket mentioned above (4547072-zen) is about a different issue though; it is not about the Tiled Gallery block. It seems they're experiencing issues with either the Pinterest block or the Image block, in the block-based widget editor. I'm not entirely sure though. @Camaropilot Could you try to gather more information and open a new issue about the problem they're facing?

Thank you!

**Comment by masperber** [comment]
33003817-hc

With this user, the error occurs when either an Image Block or a Tiled Gallery block is added to the Widget Area when using the Twenty Fifteen theme. They were able to use a Gallery Block as a workaround.

**Comment by radtechgh** [comment]
More information for 4547072-zen

Same thing happens with Image block, or Tiled Gallery block. "The editor has encountered an unexpected error." when viewed through Customizer -> Widgets. 
Adding Tiled Gallery block throws error immediately.
Image block shows error when trying to Select Image, Upload, or Insert from URL.
Scratchpad theme. 
Cannot delete Image or Tiled Gallery block.
Image block that was already there (already has image), try to select...throws error.
Pinterest block cannot be selected
Note: Appearance -> Widgets does NOT show ANY installed blocks.

TEST SITE:
Atomic. 2017 theme. 
Customizer -> Widgets, choose widget area.
Adding Tiled Gallery block throws error immediately.
Image block shows error when trying to Select Image, Upload, or Insert from URL.
Note: Can remove block by going directly to Appearance -> Widgets

**Comment by ccwalburn** [comment]
4557903-zen

This user is on the Personal plan.

Their **Customizer >  Widget** areas show an empty alt attribute error and an empty image block:

![screenshot](https://d.pr/i/V4GTgz+)
Image URL: https://d.pr/i/V4GTgz

Clicking on the Image block shows the Copy Error button, which produces this error:

```
TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/build/block-editor/index.min.js?m=1637285849h&ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:29846)
    at Qj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:876)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
    at eb (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:6339)
    at gf (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2335)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
```

The WP Admin view of Widgets shows no blocks in any of the widget areas. If I try to add a block in that view, it lets me add the block, but won't let me click the Update button.

**Comment by masperber** [comment]
32749023-hc User has the same issue when adding or interacting with an Image block in their sidebar using retired theme Affinity.

I discovered that if the sidebar widget is edited through /wp-admin/ then the error does not occur. This seems to be a viable workaround for now.

**Comment by masperber** [comment]
4567177-zen same issue when interacting with an Image block in the Customizer Widgets area. They are using a third-party theme Nucleare. Advised user to work around by going to /wp-admin/

**Comment by kdevnel** [comment]
@Camaropilot and @jeherve I've moved the issue reported [here](https://github.com/Automattic/wp-calypso/issues/56922#issuecomment-984955683) to it's own separate issue - #58835

**Comment by LauraSWP** [comment]
Related: 3623900-hc They are tiled columns gallery blocks and editing anything and saving breaks the block. Adidng an image and trying to insert it also breaks it.

**Comment by alshakero** [comment]
I closed this because fix is now in production! See p1638826754239900/1638538050.228400-slack-CBTN58FTJ
