### ISSUE TITLE
Flaky E2E: Domain Signup

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57033]
### Spec file

wp-signup__domains.ts

### Suite or step

Check out

### Framework

Playwright

### Logs

```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at CartCheckoutPage.purchase (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts:241:14)
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__domain.ts:99:22)
at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

![close-account-2021-10-14T14-55-36](https://user-images.githubusercontent.com/6549265/137365820-247eb1d7-f081-46a9-87b5-7cd859ed1580.png)

Video: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6838112:id/screenshots/close-account-2021-10-14T14-55-44.webm

Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6838112:id/trace/close-account-2021-10-14T14-55-37.zip

**Comment by worldomonation** [comment]
Observing after the above PR has been merged.

**Comment by worldomonation** [comment]
Failed in PreRelease 6904826.

It looks like extending the timeout did not help here, since the inherent issue is with the domain purchase component.

**Comment by worldomonation** [comment]
Test is in Quarantined E2E, so dropping off the sprint for now.

**Comment by worldomonation** [comment]
Closing as it has been quite some time and the Domain Signup spec needs a rework.

Work to move tests back out of Quarantined specs will be tracked in https://github.com/Automattic/wp-calypso/issues/58683.
