### ISSUE TITLE
Flaky E2E: Publish and visit post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57032]
### Spec file

wp-editor__post-basic-flow-spec.ts

### Suite or step

Publish and visit post

### Framework

Playwright

### Logs

```
frame.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".editor-post-publish-panel a:has-text("View")" to be visible
============================================================
at GutenbergEditorPage.publish (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:287:50)
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts:83:25)
```

![post-metadata-is-found-in-published-post-2021-10-14T10-11-21](https://user-images.githubusercontent.com/6549265/137362827-0a89a09e-e1d1-416a-9918-36e2ab8b6dbf.png)

Video: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6836536:id/screenshots/post-metadata-is-found-in-published-post-2021-10-14T10-11-23.webm

Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6836536:id/trace/post-metadata-is-found-in-published-post-2021-10-14T10-11-22.zip

**Comment by worldomonation** [comment]
Duplicated by #57119.
