### ISSUE TITLE
Flaky E2E: Publish and visit post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57119]
### Spec file

wp-editor__post-basic-flow-spec

### Suite or step

Publish and visit post

### Framework

Playwright

### Logs

Logs:
```
frame.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".editor-post-publish-panel a:has-text("View")" to be visible
============================================================
at GutenbergEditorPage.publish (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:287:50)
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts:83:25)
```

Video:
https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6851513:id/screenshots/post-metadata-is-found-in-published-post-2021-10-18T16-21-08.webm

Trace:
https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6851513:id/trace/post-metadata-is-found-in-published-post-2021-10-18T16-21-07.zip

Run:
https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/6851513?buildTab=overview#%2Fscreenshots;%2Ftrace

**Comment by worldomonation** [comment]
![post-metadata-is-found-in-published-post-2021-10-18T16-21-06](https://user-images.githubusercontent.com/6549265/137773825-9078dc84-cfd9-4524-a23a-059bba42d866.png)
