### ISSUE TITLE
Flaky E2E: Editor: Basic Post Flow: Publish post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57289]
### Spec file

wp-editor__post-basic-flow-spec.ts

### Suite or step

Save draft

### Framework

Playwright

### Logs

Logs:
```
frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".editor-post-save-draft"
============================================================
at GutenbergEditorPage.saveDraft (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:319:15)
at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts:114:4)
```

Run: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/6877641

Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Playwright_mobile/6877641:id/trace/post-metadata-is-found-in-published-post-2021-10-22T17-25-18.zip

**Comment by worldomonation** [comment]
This is not so much a flakey e2e as a mistake on my part.

I had forgotten that hitting `Preview` would save the post.

**Comment by worldomonation** [comment]
Fixed by the attached PR.
