### ISSUE TITLE
Playwright: Deleting invited user permissions is flaky

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57437]
### Details

See Pre-release build no. 648 - checking the delete radio when removing the recently invited user failed and is flaky. 

```
page.check: Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for selector "input[value="delete"]"
  selector resolved to visible <input type="radio" value="delete" name="radioOption" c…/>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (448.48,484)
  element does receive pointer events
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
```

**Comment by worldomonation** [comment]
Run: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/6898356?buildTab=artifacts#%2Fscreenshots;%2Ftrace

Trace: https://teamcity.a8c.com/repository/download/calypso_Calypso_E2E_Pre_Release/6898356:id/trace/close-account-2021-10-27T23-21-19.zip

**Comment by worldomonation** [comment]
Reopening since the issue resurfaced in TeamCity 6915376.

Logs this time around:
```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "input[value="delete"]:checked" to be visible
============================================================
at PeoplePage.deleteUser (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/people-page.ts:99:19)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-invite__new-user.ts:127:4)
```
