### ISSUE TITLE
Flaky E2E: Start new post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57460]
### Spec file

wp-blocks__media-spec.ts, wp-editor__post-basic-flow-spec.ts

### Suite or step

Start new post

### Framework

Playwright

### Logs

Logs:
```
page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for selector ".calypsoify.is-iframe iframe.is-loaded" to be visible
============================================================
at GutenbergEditorPage.getEditorFrame (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:88:41)
    at GutenbergEditorPage.waitUntilLoaded (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:75:28)
    at NewPostFlow.newPostFromNavbar (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/new-post-flow.ts:32:3)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-blocks__media-spec.ts:47:3)
```

Run: 6904763

**Comment by worldomonation** [comment]
I think it's the `Welcome to WordPress!` tour that's the problem.

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/139343935-6e60c72e-4a0a-4570-b3ac-613ef34bb23d.png)

**Comment by worldomonation** [comment]
Reopening issue due to some more instances of this happening.

TeamCity ID 6974976

**Comment by worldomonation** [comment]
Some more instances:

6974976
6991551
