### ISSUE TITLE
Editor: sometimes takes in excess of 60 seconds to load for Simple sites.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57485]
### Quick summary

Issue reported after being observed on end-to-end tests.

### Steps to reproduce

1. log in to account via `/log-in`.
2. start new post from navbar.
3. wait for the editor to load.

### What you expected to happen

Editor loads within an acceptable timeframe. I am unsure if we have a SLA for editor load times, but I would say a hypothetical figure of 30 seconds should be the worst case scenario.

### What actually happened

Intermittent - the editor does not finish loading by the time 60 second timeout is hit in end-to-end tests.

Note - this **does not** imply that the editor fails to load. Rather the observation is that the editor fails to load within an acceptable amount of time.

https://user-images.githubusercontent.com/6549265/139502821-db1f8e4f-64cd-4022-a5a1-55216c5327bc.mp4

### Context

Automated end to end tests.

### Simple/Atomic

Simple

### Other notes

Logs from test failure:
```
page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for selector ".calypsoify.is-iframe iframe.is-loaded"
============================================================
at GutenbergEditorPage.getEditorFrame (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:103:41)
    at GutenbergEditorPage.waitUntilLoaded (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:76:28)
    at NewPostFlow.newPostFromNavbar (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/new-post-flow.ts:32:3)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-editor__post-basic-flow-spec.ts:47:4)
```

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Likely, the user needs to reload the editor page.

**Comment by worldomonation** [comment]
Additional data:

The `start post` step is implemented on multiple tests, but the two here are notable for intermittent failures:
- wp-blocks__media-spec.ts
- wp-editor__post-basic-flow-spec.ts

They both log in as the user `e2eflowtestinggutenbergsimple`.

Following data is from TeamCity:
Failure rate across every branch for `wp-editor__post-basic-flow-spec.ts` is 45/993, roughly equal to 4.5% failure rate.

Failure rate across every branch for `wp-blocks__media-spec.ts` is similar at 43/993, again roughly equal to 4.3%.

**Comment by worldomonation** [comment]
TeamCity ID 6931057 failed to locate the iframe editor element with 105 seconds.

**Comment by jordesign** [comment]
Old TeamCity testing issue - no follow up in 3+ years so will close this.
