### ISSUE TITLE
Playwright: Handling differing dialogs when removing domain from account

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57555]
### Details

TeamCity Info: Pre-Release Tests, no. 714, ID 6921871.

```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button:has-text("Cancel Domain and Refund")"
============================================================
at IndividualPurchasePage.deleteDomain (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/individual-purchase-page.ts:105:19)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-domains__add.ts:111:4)
```

On some of our pre-release tests, we see this failure because a different dialog (can see in screenshots) popups some of the times, but not others.

**Comment by dpasque** [comment]
Looking at the [remove purchase handling here](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/remove-purchase/index.jsx), we see this dialog in the case when we are _not_ showing the non-primary domain dialog, which means in this case, we are showing the primary domain warning dialog.

It looks like this [primarily controlled by a flag ('calypso_allow_nonprimary_domains_without_plan') and whether there is a custom primary domain](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/remove-purchase/index.jsx#L166) that comes in through [props](https://github.com/Automattic/wp-calypso/blob/trunk/client/me/purchases/manage-purchase/index.jsx#L897).

**Comment by worldomonation** [comment]
I thought this is the standard dialog box for cancellations?

My suspicion was that it had to do with the clicks occurring too fast, before the `Delete this domain` button is fully rendered and ready on the page.
