### ISSUE TITLE
Flaky E2E: wp-signup__free 'Return to Calypso dashboard' - Didn't find block editor sidebar button.

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#57959]
### Details

TeamCity ID: 6968503

Looking at the video/picture, it looks like the editor just crashes as soon as it loads! It is just a blank white screen.

```
frame.getAttribute: Timeout 30000ms exceeded.
=========================== logs ===========================
  retrieving attribute "aria-expanded" from "button[aria-label="Block editor sidebar"]:visible"
============================================================
at GutenbergEditorPage.returnToCalypsoDashboard (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:390:18)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__free.ts:123:5)
```

### Checklist

- [ ]
- [ ]

**Comment by dpasque** [comment]
This was caused by a widespread editor outage, see p58i-bt1-p2

Closing!
