### ISSUE TITLE
Flaky E2E: Comment on the post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#57963]
### Spec file

wp-user__notifications.ts

### Suite or step

Comment on the post

### Framework

Playwright

### Logs

Logs:
```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at CommentsComponent.postComment (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/comments-component.ts:50:14)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-user__notifications.ts:49:4)
```

TeamCity ID: 6970336

**Comment by worldomonation** [comment]
Also seen on TeamCity ID 6970356.

These two builds ran at the same time of the day, which makes me wonder if something happened to the site at that time.

**Comment by worldomonation** [comment]
Console error when the comment field is clicked on to activate it:

```
HighlanderComments is not defined
ReferenceError: HighlanderComments is not defined
    at HTMLTextAreaElement.handler (https://e2eflowtestingnotifications.wordpress.com/2021/10/04/a-new-post-for-commenting-october-4-2021/:776:27)
```

**Comment by worldomonation** [comment]
Could be an one-off, monitoring.

**Comment by worldomonation** [comment]
This looks to be an issue related to p58i-bt1-p2, which is now resolved.
