### ISSUE TITLE
Carousel block gives "unexpected error" when converting to another block type

### ISSUE THREAD

**Issue by the-misha** [Automattic/wp-calypso#58067]
### Quick summary

User reports they're unable to convert the Carousel block (CoBlocks) to another block type, instead seeing an "unexpected error" message. Reproduced this consistently on test site. Possibly related to [this issue](https://github.com/Automattic/wp-calypso/issues/56559)?

### Steps to reproduce

1. Add a Carousel block to any page or post.
2. Populate with images.
3. Click **Carousel** button in block toolbar.
4. Hover cursor over another block type and try to click.

### What you expected to happen

Carousel block should convert to another block type.

### What actually happened

Editor displays dialog box with "The editor has encountered an unexpected error" message and three buttons: Attempt Recovery, Copy Post Text, and Copy Error.

### Context

Customer report, duplicated on test site.

### Operating System

macOS X, Windows

### Browser

Google Chrome

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No.

### Other notes

Error message:

```
TypeError: Cannot read properties of null (reading 'removeChild')
    at h.componentWillUnmount (https://tamsinsgramarye.com/wp-content/plugins/amp/assets/js/amp-block-editor.js?ver=2ee98517d90b7670631d2afc67df7285:31:1273)
    at Rh (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:43)
    at Sh (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Qj (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:174:181)
    at unstable_runWithPriority (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://tamsinsgramarye.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
```

### Reproducibility

Consistent

### Available workarounds?

No, but the platform is still usable

**Comment by jordesign** [comment]
Can we please reply to the user in #4457385-zen when this is resolved.
