### ISSUE TITLE
Widgets in Customizer crash when touching or trying to add image block

### ISSUE THREAD

**Issue by kuropixel** [Automattic/wp-calypso#58696]
### Quick summary

I have reproduced crashing when trying to access Widgets via Customizer for sidebars and footers. Adding an image block results in a crash. I am able to go the other route directly to widgets.php to add the image block, but I will experience a crash going through customizer when attempting to touch the image block.

This was tested with themes Twenty Seventeen and Gazette, both have right sidebars

Error message on Simple Site:
```
TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/build/block-editor/index.min.js?m=1637285849h&ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:29846)
    at Qj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:9:876)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
    at eb (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:6339)
    at gf (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2335)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.0.1/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
```
Error Message on Atomic site: 
```
TypeError: Cannot read properties of null (reading 'scrollTop')
    at https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js?ver=56ef77368d5b1dcf18d4c1f510f4780a:69:1731
    at Bj (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:144:41)
    at Qj (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:176:361)
    at unstable_runWithPriority (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://kuroatomic.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
```

### Steps to reproduce

1. Use a theme with a right sidebar (My case was Twenty Seventeen/Gazette)
2. Go through Customizer, then access Widgets, Sidebar or Footer.
3. Try to add an image block.
4. This results in a crash on both Simple and Atomic sites

https://user-images.githubusercontent.com/83020905/144160360-bfa9c2b6-f284-4e28-abb1-e4859ce9b1d3.mov

.

### What you expected to happen

The image block should appear so that user can add their image.

### What actually happened

"The editor has encountered an unexpected error."

### Context

Report from 4559251-zen, also confirmed on test Simple and test Atomic site.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

I've only tested on Twenty Seventeen, Lodestar, and Gazette, themes that have sidebars.

### Browser, operating system and other notes

Edge 96, macOS 11.6.1

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Going directly to widgets.php allows me to work with widgets and not experience crashes. However, that does not seem to be the case for 4559251-zen.

**Comment by Greatdane** [comment]
Confirmed, can reproduce as described.

**Comment by vinnykaur** [comment]
For 4559251-zen,

When I SU'd in Chrome, the page crashed for me. 

Screenshot:

<img width="1365" alt="Screen Shot 2021-12-02 at 10 05 44" src="https://user-images.githubusercontent.com/49183855/144358518-db476140-9ac5-4931-91ce-afd745cb3f89.png">

But when I SSO'd in Firefox, it worked fine. 

Screenshot:

<img width="1674" alt="Screen Shot 2021-12-02 at 10 07 20" src="https://user-images.githubusercontent.com/49183855/144358613-401ace23-6db2-448c-8d81-2699a9d25c06.png">

I'm going to ask them to try and use Firefox.

**Comment by vinnykaur** [comment]
> When I SU'd in Chrome, the page crashed for me.

On another note, it has now started working on chrome for me. I'll ask the user to try some browser troubleshooting.

**Comment by kuropixel** [comment]
@vinnykaur I was able to reproduce crashes every time when going through Customizer > Widgets rather than widgets.php. Are you getting crashes if you go through that method?

**Comment by vinnykaur** [comment]
> @vinnykaur I was able to reproduce crashes every time when going through Customizer > Widgets rather than widgets.php. Are you getting crashes if you go through that method?

@kuropixel Yes, I do. 

<img width="836" alt="Screen Shot 2021-12-02 at 11 10 11" src="https://user-images.githubusercontent.com/49183855/144364433-8d3791c4-3519-4a65-bba8-6282341b706b.png">

But not via widgets.php, no. That worked fine on Chrome and Firefox when I tried.

**Comment by kosiew** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/58594
