### ISSUE TITLE
Flaky E2E: Navigate to Media

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#58720]
### Spec file

wp-media__edit-spec.ts

### TeamCity ID

7056430

### Logs

```
page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector ".sidebar .selected :text-is("Media")"
  selector resolved to visible <span data-e2e-sidebar="Media" class="sidebar__menu-li…>Media</span>
============================================================
at SidebarComponent.navigate (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:86:14)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-media__edit-spec.ts:43:4)
```

**Comment by worldomonation** [comment]
Also seen in other test files.

TeamCity: 7059000
Spec: `wp-media__upload-spec.ts`
