### ISSUE TITLE
Flaky E2E: View site

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#58868]
### Spec file

wp-user__notifications.ts

### TeamCity ID

7081414

### Logs

```
page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "7Cmog-p2", waiting until "load"
============================================================
at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-user__notifications.ts:39:15)
    at Promise.then.completed (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
    at callAsyncCircusFn (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
    at jestAdapter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/144913767-041b6d02-6c39-4894-99bf-fa93266c40e0.png)

**Comment by worldomonation** [comment]
The immediate problem is that number of comments on this post has grown to the point where `page.goto` isn't able to complete loading of the page.

**Comment by worldomonation** [comment]
Immediate solution (actioned): create a new post for the tests to continue on.
