### ISSUE TITLE
Flaky E2E: Validate blog name and tagline

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59013]
### Spec file

wp-signup__free.ts

### TeamCity ID

https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Pre_Release/7103035

### Logs

Logs:
```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "input#blogname[value="e2eflowtesting1639052825440608"]" to be visible
============================================================
at GeneralSettingsPage.validateSiteTitle (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/general-settings-page.ts:73:19)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-signup__free.ts:134:31)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```
Screenshot:
![image](https://user-images.githubusercontent.com/6549265/145450066-5bc13880-5697-4e70-aa45-83ed3813e598.png)

Video
https://user-images.githubusercontent.com/6549265/145450372-cf53815c-5bf8-4dd7-bd69-079714780928.mp4

**Comment by worldomonation** [comment]
@Automattic/ganon-bloggers More of a heads up that this was observed once in the linked TeamCity build. 

The blog name in question is `e2eflowtesting1639052825440608`. I could not tell if it the name and tagline were sent as part of the network request in this screen:

![image](https://user-images.githubusercontent.com/6549265/145455270-44f21012-7f76-437a-8529-21523ef03a26.png)

However as you can see in the screenshot in the original description, the site name and tagline were not set properly, instead defaulting to the standard one.

**Comment by worldomonation** [comment]
Superseded by https://github.com/Automattic/wp-calypso/issues/64271, where we find the behavior is in fact a bug.
