### ISSUE TITLE
Carousel Block crashes page if added when any other block is selected

### ISSUE THREAD

**Issue by Greatdane** [Automattic/wp-calypso#59093]
### Quick summary

**Note 1: This is a CoBlocks Block - so probably needs to be posted on there once it has been triaged/reproduced.** 
**Note 2: I have reproduced this on self-hosted and Atomic sites.** 

If you have a block already selected and then use the [ + ] button on the top left of the editor and choose Carousel Block the editor crashes with an error, `The editor has encountered an unexpected error.`

Error Log;

```
TypeError: Cannot read properties of null (reading 'removeChild')
    at h.componentWillUnmount (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/amp/assets/js/amp-block-editor.js?ver=2ee98517d90b7670631d2afc67df7285:31:1273)
    at Rh (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:43)
    at Sh (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Qj (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:174:181)
    at unstable_runWithPriority (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
    at https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://dwtestatbugherding.wpcomstaging.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
```

### Steps to reproduce

1. Create a page or post.
2. Add a block, any block. (tested Image, Heading, Paragraph)
3. While that block is selected, click the [ + ] icon and choose Carousel Block.
4. The page will crash and you can a `The editor has encountered an unexpected error.` message.

Video;

https://user-images.githubusercontent.com/5075840/145663447-767192b1-95ac-41bf-b0c5-92df8d2150c6.mp4

### What you expected to happen

Should be able to add the block without the editor crashing!

### What actually happened

Editor Crashed when adding block. 

### Context

User Report. 

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by Robertght** [comment]
Closing this one in favor of this: https://github.com/Automattic/wp-calypso/issues/56559

**Comment by Greatdane** [comment]
@Robertght #56559 looks to have been closed by GoDaddy; https://github.com/godaddy-wordpress/coblocks/issues/2042

So I am wondering if this is a different issue? Console errors also seem to be different. 

It may be prudent for me to post this on The CoBlocks repo if someone else can reproduce it when triaging?

**Comment by Robertght** [comment]
No worries! I've linked these to the same issue on CoBlocks's end for now, however, although the error appear somewhat different the pattern seems to be the same.

I'll circle back once we hear back from the devs.
