### ISSUE TITLE
Flaky E2E: Open and close SEO preview

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59327]
### Spec file

wp-seo__preview.ts

### TeamCity ID

https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/7132157

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".web-preview.is-seo" to be visible
============================================================
at MarketingPage.openSEOPreview (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/marketing-page.ts:56:19)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-seo__preview-spec.js:41:3)
```

Possibly related to https://github.com/Automattic/wp-calypso/commit/022d6c3866fbd22e632ef2863d803835bdcfa0f3, but not 100% established. Moderately strong possibility that it is related however, due to this failure cropping up for the first time immediate after merge of #59146.

**Comment by worldomonation** [comment]
Duplicated by #59918
