### ISSUE TITLE
Flaky E2E: Open and close SEO preview

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59918]
### Spec file

wp-seo__preview-spec.js

### TeamCity ID

7224714

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".web-preview.is-seo" to be visible
============================================================
at MarketingPage.openSEOPreview (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/marketing-page.ts:56:19)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-seo__preview-spec.js:41:3)
```

**Comment by worldomonation** [comment]
Reopening because it failed once more in https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_desktop/7282137?buildTab=tests#%2Fscreenshots.
