### ISSUE TITLE
Flaky E2E: Insert Cover block

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#59929]
### Spec file

wp-blocks__coblocks__extensions__cover-styles.ts:

### TeamCity ID

7220861

### Logs

```
frame.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[aria-label="Block: Cover"].is-selected" to be visible
  selector resolved to hidden <div tabindex="0" role="document" data-title="Cover" …>…</div>
============================================================
at GutenbergEditorPage.addBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:269:22)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-blocks__coblocks__extensions__cover-styles.ts:45:23)
```

**Comment by worldomonation** [comment]
![](https://teamcity.a8c.com/repository/download/calypso_WPComTests_gutenberg_Playwright_desktop/7220861:id/screenshots/wp-blocks__coblocks__extensions__cover-styles-insert-cover-block.png)

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/148853174-f325d96b-7e12-4127-ad9b-9acaaad5ded0.png)
