### ISSUE TITLE
Image block transform block option giving error on hovering on the options

### ISSUE THREAD

**Issue by galakhyati** [Automattic/wp-calypso#60353]
### Quick summary

User has Image block within a Layout Grid which is within a Group block.

When they try to click on the Transform option on the Image block and hover on the options listed they are seeing the message `The editor has encountered an unexpected error`.

I was able to replicate the issue on the user's site. User's site screencast video: 

https://user-images.githubusercontent.com/7382505/150623691-cfb483d5-6892-46f8-b016-a1174d29e109.mp4

When I copied the user's content and tested it on my test site, I was able to replicate the issue there too. My test site video:

https://user-images.githubusercontent.com/7382505/150623708-28ea8ae8-0caf-4a76-99ab-9e37dfbffcae.mp4

### Steps to reproduce

1. Have an Image block on the page
2. Click on the Transform Block option.
3. Hovering on the options is showing the error message: `The editor has encountered an unexpected error`.

### What you expected to happen

No error is to be shown.

### What actually happened

Able to continue editing the blocks and transform the block to some other block.

### Context

Customer report. 

Chat: 33791170-hc
Follow-up: 4709798-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by galakhyati** [comment]
Another user gets the same error when trying to add the Carousel block by browsing through the blocks to add. 

I was able to replicate the issue on my test AT site: 

https://user-images.githubusercontent.com/7382505/151645752-05c97650-e855-42f4-860d-c64a5f78fc75.mp4


Here is a recording the user shared with us:

https://user-images.githubusercontent.com/7382505/151645880-2780052a-8aa6-4d78-899b-a13e65c12a34.mov

Ticket: #4716825-zen

**Comment by rw-ye** [comment]
User reached out to us again - 4745251-zd-woothemes

User wanted to add:
>I found that not only when I select the image block cause the error, but also when I select all types of the block will cause the error.
Hope this information can help.

**Comment by CompChris** [comment]
I have another user that this is happening to, when hovering over the Carousel block (and possibly others). 

12162856-hc
4747656-zd

--Gutenberg plugin on--

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Sh (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:152:147)
    at Rh (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:115)
    at Sh (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Rh (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:115)
    at Sh (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Qj (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:174:181)
    at unstable_runWithPriority (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://la-parenthese-de-chacha.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)

--Gutenberg plugin off--

TypeError: Cannot read properties of null (reading 'removeChild')
    at b.componentWillUnmount (https://la-parenthese-de-chacha.com/wp-content/plugins/amp/assets/js/amp-block-editor.js?ver=4d939a6970d38864f030d7537f1b419c:11:1272)
    at Rh (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:148:43)
    at Sh (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:151:394)
    at Qj (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:174:181)
    at unstable_runWithPriority (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26)
    at Za (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8)
    at eb (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:170:163)
    at gf (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:162:317)
    at https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
    at unstable_runWithPriority (https://la-parenthese-de-chacha.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26)

**Comment by Greatdane** [comment]
Can replicate when embedding an image into a layout grid and trying to transform image;

https://user-images.githubusercontent.com/5075840/153342513-a617c8c6-bd17-4be7-9e0d-0db3f12465b8.mov

**Comment by ajaykj** [comment]
> User reached out to us again - 4745251-zd-woothemes
> 
> User wanted to add:
> 
> > I found that not only when I select the image block cause the error, but also when I select all types of the block will cause the error.
> > Hope this information can help.

I am closing that ticket as it has been on hold for 23 days. Please create a new follow-up ticket when the issue is solved.

**Comment by druesome** [comment]
Once this is resolved, please update the user in 4823974-zd-woothemes.  I've put the ticket on hold.

**Comment by Robertght** [comment]
For the case above, turning off CoBlocks helped initially, however, it appears the websites are running an outdated version, 2.19.1.  This needs to be removed through CLI/SFTP and installed fresh through the Plugins page **by uploading the plugin zip file.**

cc @ajaykj @Greatdane @CompChris @rw-ye @galakhyati 

bcc @inaikem

**Comment by devNigel** [comment]
Another case: 4872820-zen

Tried deleting from CLI / SFTP as suggested by @Robertght above. Deleted symlink from SFTP as well. But still, when installing CoBlocks again, 2.19.1 was getting installed instead of the latest version.

Please update the user once it is fixed.

**Comment by JoshuaGoode** [comment]
Discussed managed Atomic version updates internally.

p9o2xV-1Yw-p2

**Comment by Robertght** [comment]
I have followed up with all the users above.

This is safe to be closed now, but please reopen if you encounter more reports.
