### ISSUE TITLE
Flaky E2E: Close account is interrupted by a Calypso redirect navigation

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#60555]
### Spec file

wp-gutenboarding__happy-paths.ts

### TeamCity ID

7312768

### Logs

```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".sidebar a:has(span:has-text("Account Settings")), .sidebar a[href="Account Settings"]"
  selector resolved to visible <a href="/me/account" class="sidebar__menu-link">…</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
element was detached from the DOM, retrying
waiting for selector ".sidebar a:has(span:has-text("Account Settings")), .sidebar a[href="Account Settings"]"
  selector resolved to hidden <a href="/me/account" class="sidebar__menu-link">…</a>
attempting click action
  waiting for element to be visible, enabled and stable
element is not visible - waiting...
  element is visible, enabled and stable
element was detached from the DOM, retrying
waiting for selector ".sidebar a:has(span:has-text("Account Settings")), .sidebar a[href="Account Settings"]"
============================================================
    at MeSidebarComponent.navigate (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/me/me-sidebar-component.ts:32:14)
    at CloseAccountFlow.closeAccount (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/close-account-flow.ts:30:28)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-gutenboarding__happy-path.ts:74:4)

```

If you watch the video, it's clear that there's a redirect back to home that occurs, detaching the element.

This means in this flow, we probably need to wait when logging in for the redirect to home before progressing on to the close account page.

**Comment by worldomonation** [comment]
Looks like you got to filing an issue before I did! 

https://github.com/Automattic/wp-calypso/issues/60572

**Comment by worldomonation** [comment]
I'll take this on today.
