### ISSUE TITLE
Flaky E2E: Insert a Legacy Widget

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#60582]
### Spec file

specs/specs-wpcom/wp-widgets__spec.ts

### TeamCity ID

7309843

### Logs

Log:
```
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button[aria-label="Add block"]"
  selector resolved to 2 elements. Proceeding with the first one.
  selector resolved to visible <button type="button" aria-haspopup="true" aria-expanded…>…</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #4
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #5
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #6
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #7
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #8
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #9
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #10
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #11
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #12
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #13
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #14
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #15
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #16
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #17
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #18
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #19
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #20
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #21
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #22
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #23
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #24
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #25
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #26
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #27
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #28
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #29
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #30
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #31
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #32
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #33
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #34
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #35
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #36
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #37
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #38
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #39
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #40
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #41
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #42
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #43
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #44
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #45
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #46
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #47
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #48
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #49
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #50
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #51
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #52
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #53
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #54
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #55
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #56
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #57
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #58
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #59
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #60
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #61
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (580,214)
  <img alt="" scale="0" width="312" height="240" src="h…/> from <div class="components-modal__screen-overlay">…</div> subtree intercepts pointer events
retrying click action, attempt #62
  waiting 500ms
============================================================
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-wpcom/wp-widgets__spec.ts:48:16)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:390:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:315:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:167:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

![image](https://user-images.githubusercontent.com/6549265/151426858-31e7ce2f-5399-439c-ba4a-2667329f5cd6.png)

**Comment by worldomonation** [comment]
It has to do with English US/UK, where English UK uses `dialogue` and English US uses `dialog`.
![Screen Shot 2022-01-27 at 11 15 58 AM](https://user-images.githubusercontent.com/6549265/151428272-21f0f88e-96e8-4158-9b0b-b494b849d68d.png)


![Screen Shot 2022-01-27 at 11 16 23 AM](https://user-images.githubusercontent.com/6549265/151428267-f586d488-1d78-4428-bd64-cc4f9cac14d0.png)
