### ISSUE TITLE
Flaky E2E: Click on the "My Plan" tab

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#61095]
### Spec file

specs/specs-playwright/wp-plans__purchases-spec.ts

### TeamCity ID

7401779

### Logs

```
locator.waitFor: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".section-nav__panel" to be visible
  selector resolved to hidden <div class="section-nav__panel">…</div>
============================================================
at clickNavTab (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/element-helper.ts:57:25)
    at PlansPage.clickTab (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/plans-page.ts:84:3)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/specs-playwright/wp-plans__purchases-spec.ts:38:4)
```

Link: https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Playwright_mobile/7401779?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

**Comment by worldomonation** [comment]
Incidence of this test flaking out has increased.
Statistics from TeamCity across all branches:

14 failed
441 successful
145 ignored

**Comment by worldomonation** [comment]
Muted test for now.

**Comment by worldomonation** [comment]
https://github.com/Automattic/wp-calypso/issues/64389 is the same issue and should have ultimately been solved in https://github.com/Automattic/wp-calypso/pull/64421.
