### ISSUE TITLE
Flaky E2E: Add Heading

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#61272]
### Spec file

specs/editor/editor__post-basic-flow.ts

### TeamCity ID

7429305

### Logs

Link: https://teamcity.a8c.com/buildConfiguration/calypso_WPComTests_gutenberg_Playwright_desktop/7429305?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

Logs:
```
frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "div[aria-label="Heading"]"
============================================================
at GutenbergEditorPage.addPattern (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/gutenberg-editor-page.ts:329:15)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:73:4)
```

**Comment by worldomonation** [comment]
Issue worked around in  #61376.
