### ISSUE TITLE
When viewing Lessons, WooCommerce PayPal Checkout Gateway displays Critical Error with Sensei LMS

### ISSUE THREAD

**Issue by edwinho89** [Automattic/wp-calypso#61393]
### Quick summary

When attempting to view lessons under Sensei LMS, the lessons lead to a 500/critical error from `class-wc-gateway-ppec-ips-handler.php:102`

Reported on 32606993-hc

Bug report should be moved under https://github.com/woocommerce/woocommerce-paypal-payments

### Steps to reproduce

Visit any of the lessons in https://jimsdigitalmarketing.com/course/facebook-ads/

### What you expected to happen

Doing so allows visiting the lesson page seamlessly.

### What actually happened

The following critical error with message as below:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_base_country() on null in /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/class-wc-gateway-ppec-ips-handler.php:102
Stack trace:
#0 /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/settings/settings-ppec.php(15): WC_Gateway_PPEC_IPS_Handler->is_supported()
#1 /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/abstracts/abstract-wc-gateway-ppec.php(118): include('/wordpress/plug...')
#2 /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/abstracts/abstract-wc-gateway-ppec.php(23): WC_Gateway_PPEC->init_form_fields()
#3 /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/class-wc-gateway-ppec-with-paypal.php(12): WC_Gateway_PPEC->__construct()
#4 /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/class-wc-gateway-ppec-with-spb.php(12): WC_Gateway_PPEC_With_PayPal->__construct()
#5 /wordpress/plugins/woocommerce/6.2.0/includes/class-wc-payment-gateways.php(97): WC_Gateway_PPEC_With_SPB->__construct()
#6 /wordpress/plugins/woocommerce/6.2.0/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init()
#7 /wordpress/plugins/woocommerce/6.2.0/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct()
#8 /wordpress/plugins/woocommerce/6.2.0/includes/class-woocommerce.php(888): WC_Payment_Gateways::instance()
#9 /wordpress/plugins/woocommerce-gateway-stripe/6.2.0/includes/class-wc-stripe-intent-controller.php(52): WooCommerce->payment_gateways()
#10 /wordpress/plugins/woocommerce-gateway-stripe/6.2.0/includes/class-wc-stripe-intent-controller.php(678): WC_Stripe_Intent_Controller->get_gateway()
#11 /wordpress/core/5.9.1/wp-includes/class-wp-hook.php(307): WC_Stripe_Intent_Controller->maybe_process_upe_redirect(Object(WP))
#12 /wordpress/core/5.9.1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#13 /wordpress/core/5.9.1/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#14 /wordpress/core/5.9.1/wp-includes/class-wp.php(771): do_action_ref_array('wp', Array)
#15 /wordpress/core/5.9.1/wp-includes/functions.php(1310): WP->main('')
#16 /srv/htdocs/wp-content/plugins/sensei-lms/includes/course-theme/class-sensei-course-theme.php(127): wp()
#17 /wordpress/core/5.9.1/wp-includes/class-wp-hook.php(307): Sensei_Course_Theme->maybe_override_theme('')
#18 /wordpress/core/5.9.1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#19 /wordpress/core/5.9.1/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#20 /wordpress/core/5.9.1/wp-settings.php(519): do_action('setup_theme')
#21 /srv/htdocs/wp-config.php(81): require_once('/wordpress/core...')
#22 /wordpress/core/5.9.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#23 /wordpress/core/5.9.1/wp-blog-header.php(13): require_once('/wordpress/core...')
#24 /wordpress/core/5.9.1/index.php(17): require('/wordpress/core...')
#25 {main}
  thrown in /wordpress/plugins/woocommerce-gateway-paypal-express-checkout/2.1.3/includes/class-wc-gateway-ppec-ips-handler.php on line 102
```

### Context

- WordPress Version: 5.9.1
- WooCommerce Version 6.2.0
- WooCommerce PayPal Checkout Gateway Version 2.1.3
- Sensei LMS Version 4.0.2

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Deactivate WooCommerce PayPal Checkout Gateway plugin.

**Comment by Greatdane** [comment]
Based on the error code, It looks like this relates to https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/ - which has been discontinued since March 2022.

@Automattic/proton - is this your area? Or can you point us to the right team to confirm support for this plugin has finished? 🙇

**Comment by barryhughes** [comment]
Hi! It's not a Proton extension ... I *think* perhaps this is @Automattic/axiom territory (but my apologies if I'm wrong 😁).

**Comment by LCmry** [comment]
Hello! This is indeed under Axiom. And you are correct it is sunsetted and support discontinued. Are there any workarounds or pinpointing that we can help with?

**Comment by leonardola** [comment]
The recommended way to tackle this, is to disable and remove paypal express checkout and then install https://woocommerce.com/products/woocommerce-paypal-payments/ which is still being supported

**Comment by Greatdane** [comment]
Thank you all! Closing this isssue.

cc: @edwinho89
