### ISSUE TITLE
Marketplace: Yoast SEO Premium doesn't get active after installation

### ISSUE THREAD

**Issue by cpapazoglou** [Automattic/wp-calypso#61800]
After buying Yoast SEO Premium, both Yoast SEO and Yoast SEO Premium get installed but `Yoast SEO Premium` is not active.

![CleanShot 2022-03-10 at 15 44 33@2x](https://user-images.githubusercontent.com/12430020/157674361-c70d61ae-8a0a-4751-809f-dbd81bada398.png)

**Comment by cpapazoglou** [comment]
Related: p9o2xV-1sG-p2#comment-4778

**Comment by cpapazoglou** [comment]
Plugins in the Atomic infrastructure are installed via WP CLI
`wp --skip-plugins --skip-themes plugin activate wordpress-seo-premium` which returns the following error
```
Fatal error: Uncaught Error: Class 'WPSEO_Capability_Manager_Factory' not found in /wordpress/plugins/wordpress-seo-premium/18.2.1/premium.php:79
Stack trace:
#0 /wordpress/core/5.9.2/wp-includes/class-wp-hook.php(307): WPSEO_Premium::install(NULL)
#1 /wordpress/core/5.9.2/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/5.9.2/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /wordpress/core/5.9.2/wp-admin/includes/plugin.php(689): do_action('activate_wordpr...', NULL)
#4 phar:///usr/local/bin/wp-cli/vendor/wp-cli/extension-command/src/Plugin_Command.php(333): activate_plugin('wordpress-seo-p...', '', NULL)
#5 [internal function]: Plugin_Command->activate(Array, Array)
#6 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(417): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(440): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#13 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#14 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#15 phar:///usr/local/bin/wp-cli/php/boot-phar.php(11): include('phar:///usr/loc...')
#16 /usr/local/bin/wp-cli(4): include('phar:///usr/loc...')
#17 {main}
  thrown in /wordpress/plugins/wordpress-seo-premium/18.2.1/premium.php on line 79
```

@epeicher can you follow up with Yoast in cSRhZ-p2 for the to fix that error?

**Comment by epeicher** [comment]
P2 written to follow up with Yoast pcSRhZ-34-p2

**Comment by epeicher** [comment]
P2 written to ask Atomic team for a potential solution pdh6GB-zu-p2 

They suggested a change that has been implemented in the diff below.

Diff created D78193-code

**Comment by cpapazoglou** [comment]
Deployed r243219-wpcom which activates the plugins through CLI and works for test users (me and @epeicher).

We still need to remove the test users checks.

**Comment by epeicher** [comment]
Additional diff created removing the test users check.

D78308-code
