### ISSUE TITLE
Flaky E2E: Onboarding Import Can't Find Continue Button

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#62596]
### Spec file

onboarding/start__importer.ts

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".content-chooser .import-layout__column:nth-child(2) > div > div:last-child button:text("Continue")" to be visible
    ============================================================

      108 | 	 */
      109 | 	async validateWordPressPage(): Promise< void > {
    > 110 | 		await this.page.waitForSelector( selectors.wpContentOnlyContinueButton );
          | 		                ^
      111 | 	}
      112 |
      113 | 	/**

      at StartImportFlow.validateWordPressPage (../../packages/calypso-e2e/src/lib/flows/start-import-flow.ts:110:19)
      at Object.<anonymous> (specs/onboarding/start__importer.ts:42:26)

```

**Comment by worldomonation** [comment]
I think I may have done this for https://github.com/Automattic/wp-calypso/pull/65797.
