### ISSUE TITLE
Flaky E2E: Validate post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#63036]
### Spec file

specs/editor/editor__post-advanced-flow.ts

### TeamCity ID

7782243

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "p:text("11 Healthy Crows Howl Clearly")" to be visible
============================================================
at Function.validatePublishedContent (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/paragraph-block.ts:46:15)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:72:4)
```

![image](https://user-images.githubusercontent.com/6549265/165227983-9216fd14-1e58-4317-8bf5-9476f65c94f8.png)

**Comment by worldomonation** [comment]
I don't think this has happened in some time. Closing for now
