### ISSUE TITLE
Flaky E2E: Editor tracking: FSE edge site sometimes has gray overlay when adding blocks

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#65094]
### Spec file

editor-tracking__fse-template-events.ts (but really, any test that tests FSE on the edge site)

### TeamCity ID

8146603

### Logs

```
waiting for selector "iframe.is-loaded[src*="wp-admin/themes.php"] >> control=enter-frame >> body.block-editor-page >> [aria-label="Block tools"] button[aria-label="Options"]"
  selector resolved to visible <button type="button" tabindex="-1" id="id-llvc53-4" ari…>…</button>
attempting click action
...
retrying click action, attempt #50
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is outside of the viewport
retrying click action, attempt #51
  waiting 500ms
============================================================
at EditorBlockToolbarComponent.clickOptionsButton (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-block-toolbar-component.ts:55:17)
    at FullSiteEditorPage.clickBlockToolbarOption (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:332:3)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor-tracking/editor-tracking__fse-template-events.ts:195:5)
```

In any case where you add a block in the FSE edge site site-editor, in some cases, the screen becomes gray, and that gray shield covers any action in the editor.

See this picture:
![fse-gray-screen](https://user-images.githubusercontent.com/26772342/176503838-99afb901-dc6d-4ffa-8f97-2de71dafd696.png)

It never reproduces manually 🤔 . Not sure what is going on here, but it deserves looking at!

**Comment by worldomonation** [comment]
To whomever that ends up working on this, verify that this is indeed still an issue.

**Comment by worldomonation** [comment]
Likely no longer an issue.
