### ISSUE TITLE
Flaky E2E: Revoke the invite for test user

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#65566]
### Spec file

test/e2e/specs/users/invite__revoke.ts

### TeamCity ID

8218365

### Logs

```
page.waitForNavigation: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation to "**/people/invites/**" until "networkidle"
  navigated to "https://container-intelligent-benz.calypso.live/people/invites/e2eflowtesting4.wordpress.com"
============================================================
at PeoplePage.clickTab (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/people-page.ts:58:15)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/users/invite__revoke.ts:74:20)
```

**Comment by worldomonation** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/65612.
