### ISSUE TITLE
npm pre-hook to setup config for tests

### ISSUE THREAD

**Issue by samouri** [Automattic/wp-calypso#6605]
Part of issue #4915 

Right now unit tests will not run if the module `config` does not exist and will throw an error like this:

```
wp-calypso (add/watch-tests-chokidar) $ npm run test-client:watch

> wp-calypso@0.17.0 test-client:watch /Users/andrew/Documents/Code/wp-calypso
> NODE_ENV=test NODE_PATH=test:client TEST_ROOT=client nodemon -e js,jsx --exec npm run test-client

7 Jul 09:59:57 - [nodemon] v1.4.1
7 Jul 09:59:57 - [nodemon] to restart at any time, enter `rs`
7 Jul 09:59:57 - [nodemon] watching: *.*
7 Jul 09:59:57 - [nodemon] starting `npm run test-client`

> wp-calypso@0.17.0 test-client /Users/andrew/Documents/Code/wp-calypso
> NODE_ENV=test NODE_PATH=test:client TEST_ROOT=client test/runner.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (index.js:6:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/andrew/Documents/Code/wp-calypso/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/andrew/Documents/Code/wp-calypso/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

It would be ideal if this sequence was successful:
1. git clone
2. npm install
3. npm run test-client

One potential way to solve it would be to have a prehook for any tests to run: `make client/config/index.js`.

**Comment by gziolo** [comment]
There is already another `config` related issues: #5856. My proposed solution was to always generate on the fly config fly when executing tests. Otherwise it can be almost impossible to have app running using `development` env and tests running with watch using `test` env.

**Comment by samouri** [comment]
Potential solution is here: https://github.com/Automattic/wp-calypso/pull/11352

**Comment by gziolo** [comment]
This is no longer an issue since #11352 landed :)
