### ISSUE TITLE
Flaky E2E: Land in Home dashboard

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#66228]
### Spec file

ftme__sell.ts

### TeamCity ID

8334868

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".primary__customer-home-location-content :text("Update your site's design")" to be visible
============================================================
at MyHomePage.validateTaskHeadingMessage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/my-home-page.ts:45:19)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__sell.ts:179:21)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/6549265/182665831-6d6bb26d-3c10-4a74-ac54-014be3787980.png)

**Comment by worldomonation** [comment]
Video:
[ftme__sell__land-in-home-dashboard__0-0.webm](https://user-images.githubusercontent.com/6549265/182665993-0fd23bb7-3a9e-4035-9863-fd5a0836e57f.webm)

**Comment by worldomonation** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/66230.
