### ISSUE TITLE
Flaky E2E: Select a free .wordpress.com domain

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#67400]
### Spec file

plans__signup-free.ts

### TeamCity ID

8531313

### Logs

```
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".domain-suggestion__content:has-text(".wordpress.com")" to be visible
============================================================
at DomainSearchComponent.selectDomain (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/domain-search-component.ts:57:38)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/plans/plans__signup-free.ts:59:33)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/188491945-b216c4a3-3477-4635-bae6-b2b8a01d6c90.png)
