### ISSUE TITLE
Flaky E2E: Install plugin

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#68457]
### Spec file

specs/jetpack/plugins__install-remove.ts

### TeamCity ID

8699100

### Logs

```
page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response /.*install\?.*/
============================================================
at PluginsPage.clickInstallPlugin (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/plugins-page.ts:330:34)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/jetpack/plugins__install-remove.ts:49:22)
    at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

and its related failure:

```
locator.waitFor: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "div.notice.is-success :text("Successfully installed and activated Hello Dolly on jetpackstable.mystagingwebsite.com")" to be visible
============================================================
at NoticeComponent.noticeShown (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/notice-component.ts:57:17)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/jetpack/plugins__install-remove.ts:56:26)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/193161554-802dc177-e0e3-43a4-ac77-b00b1115e464.png)

[plugins__install-remove__return-to-hello-dolly-page__0-0.webm](https://user-images.githubusercontent.com/6549265/193161588-41b8572a-402f-4de5-8999-f3ae58aeb373.webm)

**Comment by worldomonation** [comment]
This test may benefit from expanding the capability of the [`RestAPIClient`](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/rest-api-client.ts) to perform plugin installation/uninstallation tasks.

**Comment by karenroldan** [comment]
I am able to replicate the issue even on my local. I can start looking into this!

**Comment by karenroldan** [comment]
Looking at the [recent runs of this test](https://teamcity.a8c.com/repository/download/calypso_WPComTests_jetpack_Playwright_desktop/9108979:id/screenshots/plugins__install-remove__install-plugin__0-0.webm), the plugin is already installed but not activated. 

And `pluginsPage.pluginIsInstalled()` in `beforeAll()` is not returning true because the element specified for the plugin toggle no longer exists.

One more observation is when removing the plugin from the plugin page, there is a toggle menu now before you can click on the remove button. Although I wasn't sure what the UI looked like before, so I might be wrong. 

### Suggestions:
We can utilize the REST API `/me/sites/plugins` in the `beforeAll()` to get the installed plugins of the site and also check if plugin is activated or not. 

The [API](https://developer.wordpress.com/docs/api/1.1/get/me/sites/plugins/) returns sites: list of current user's sites plugins keyed by blog_id. 

I couldn't get a programmatic way to get the blog_id yet so I hardcoded it (I took it from the Blog RC) which could not be a good solution. 

If it is installed, we can use REST API also to uninstall the plugin. I can leave the install/remove plugin tests as it is. 

Let me know your thoughts @worldomonation 😄 

### Next steps:
I would need to read and understand the WordPress.com REST API especially I don't see an API to remove plugin from the [docs](https://developer.wordpress.com/docs/api/).

**Comment by worldomonation** [comment]
@karenroldan Thanks for the detailed write-up!

> We can utilize the REST API /me/sites/plugins in the beforeAll() to get the installed plugins of the site and also check if plugin is activated or not.

Yes, I was going to suggest going down this route too. It would be much more reliable than querying the installed plugins page.

> I don't see an API to remove plugin from the [docs](https://developer.wordpress.com/docs/api/).

The docs are completely out of date and do not include any reference to a large number of actually available calls. 
It's not the best, but I would suggest going to the [Developer Console](https://developer.wordpress.com/docs/api/console/) (make sure to log in as one of your test accounts just in case you want to try something potentially destructive) and play around with the available methods. Searching for `plugin` in the top bar returns some methods that might be useful:

![image](https://user-images.githubusercontent.com/6549265/206531489-b7108351-464f-42b7-847f-626eed22d703.png)

> I couldn't get a programmatic way to get the blog_id yet so I hardcoded it (I took it from the Blog RC) which could not be a good solution.

In `RestAPIClient` there should be a method to obtain all blogs that belong to a site. 
Also, looking at the decrypted secrets file, notice there are two schemas available - one with a lot of metadata such as `testSites` and another schema which is pretty sparse. 

I'm slowly transitioning our `testAccounts` values to the newer schema that tracks username, userID, testSite id, etc. The test account used for this spec might not yet be updated to the new schema, but it would be a one-time work to do so. Let me know if this didn't make sense, I am happy to go over it with you on Slack :)
