### ISSUE TITLE
Flaky E2E: Onboarding - Select "Travel Agencies & Services" category

### ISSUE THREAD

**Issue by karenroldan** [Automattic/wp-calypso#70945]
### Spec file

specs/onboarding/setup__build.ts

### TeamCity ID

9127710

### Logs

```
page.waitForLoadState: Timeout 20000ms exceeded.
at StartSiteFlow.enterVertical (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/start-site-flow.ts:100:19)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__build.ts:42:25)
    at Promise.then.completed (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by karenroldan** [comment]
Timeout was extended to 30000ms (30 seconds) in #70932 but `waitForLoadState` on `networkidle` is still failing. 

I couldn't replicate the issue locally. 

Here's what I found from the trace file in [Artifacts](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Calypso_E2E_Playwright_mobile/9127710?buildTab=artifacts). 
![oFbxfi.png](https://user-images.githubusercontent.com/67279475/206471774-7aff5e12-886c-4649-a35e-f6b96d685a89.png)

**Comment by karenroldan** [comment]
Related fix: #71080 

We can keep this open for now to monitor if the issue will still occur.

**Comment by worldomonation** [comment]
Quarantined the spec in https://github.com/Automattic/wp-calypso/pull/71358.

**Comment by worldomonation** [comment]
Returning to Backlog status as the spec is quarantined, but the issue will likely surface once returned to production.

**Comment by worldomonation** [comment]
@arthur791004 Hey, just wanted to let you know that this spec has been in quarantine since late December 2022 and has not been running for some time due to this issue.
