### ISSUE TITLE
Flaky E2E: Select "Travel Agencies & Services" category

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#71357]
### Spec file

setup__build.ts

### TeamCity ID

9190864

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.suggestions__item :text("Travel Agencies & Services")')
============================================================
at StartSiteFlow.enterVertical (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/start-site-flow.ts:106:31)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__build.ts:44:5)
```

**Comment by worldomonation** [comment]
@arthur791004 I've quarantined this spec in #71358 because of the very high rate of intermittent failures:

![image](https://user-images.githubusercontent.com/6549265/208551944-1fec8cfe-72d9-45c6-94d1-9ad172c356f7.png)

**Comment by karenroldan** [comment]
Duplicate of #70945

**Comment by worldomonation** [comment]
Closing as duplicate.
