### ISSUE TITLE
Atomic - Better wpcomsh Error Messages when Jetpack is Deactivated

### ISSUE THREAD

**Issue by mxhassani** [Automattic/wp-calypso#71491]
### What

Right now, when Jetpack is deactivated, there are cases where wpcomsh throws a generic critical error and prevents users from accessing wp-admin due to that.

What about showing a message or clear notification (email?) that Jetpack needs to be ON for the site to work correctly?

### Why

Right now, when Jetpack is deactivated, there are cases where wpcomsh throws a fatal error, like this one:

```
[23-Dec-2022 11:53:20 UTC] PHP Fatal error:  Uncaught Error: Class 'Automattic\Jetpack\Status' not found in /wordpress/plugins/wpcomsh/3.5.14/vendor/automattic/wc-calypso-bridge/class-wc-calypso-bridge-shared.php:99
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_Calypso_Bridge_Shared->add_extension_register_script('index.php')
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/core/6.1.1/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'index.php')
#4 /wordpress/core/6.1.1/wp-admin/index.php(137): require_once('/wordpress/core...')
#5 {main}
  thrown in /wordpress/plugins/wpcomsh/3.5.14/vendor/automattic/wc-calypso-bridge/class-wc-calypso-bridge-shared.php on line 99
```

This causes the user to see a generic WordPress critical error message on wp-admin pages:

```
There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

I am not exactly sure what are the conditions that lead to that happening, but Jetpack being off is a known cause for that (Slack search `/vendor/automattic/wc-calypso-bridge/`)

Since we are in full control of both plugins, having an impeding critical error on wp-admin may not be the best way to communicate the issue with users.

### How

Add a logic check in `wpcomsh` before the call in `class-wc-calypso-bridge-shared.php:99`, then display the page or send an email to the user if Jetpack is OFF.

Some opinions about the topic are shared here: p1671797395238149-slack-C03TY6J1A

**Comment by zachspears** [comment]
I think this would be very helpful for individuals troubleshooting their site's connection. Marking low priority due to lo impact.
