### ISSUE TITLE
Flaky E2E: Add About Me pattern

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72184]
### TeamCity ID

specs/editor/editor__post-basic-flow.ts

### Logs

```
locator.hover: Timeout 10000ms exceeded.
=========================== logs ===========================
  waiting for frameLocator('iframe.is-loaded')
  locator resolved to visible <iframe class="is-loaded" src="https://e2eflowtestinggut…></iframe>
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page').locator('.block-editor-inserter__main-area div[aria-label="About Me"]').first()
  locator resolved to visible <div tabindex="-1" role="option" id="id-l2h9hu-2" ari…>…</div>
attempting hover action
  waiting for element to be visible and stable
  element is visible and stable
  scrolling into view if needed
  done scrolling
============================================================
at EditorSidebarBlockInserterComponent.selectBlockInserterResult (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts:80:32)
    at EditorPage.addPatternFromInserter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:368:18)
    at EditorPage.addPatternFromSidebar (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:330:3)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:61:4)
```

**Comment by worldomonation** [comment]
Closing as it has not been seen since.
