### ISSUE TITLE
Flaky E2E: Enter post content

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72298]
### Spec file

specs/editor/editor__post-advanced-flow.ts

### Logs

```
locator.hover: Timeout 10000ms exceeded.
=========================== logs ===========================
  waiting for frameLocator('iframe.is-loaded')
  locator resolved to visible <iframe class="is-loaded" src="https://e2eflowtestingsim…></iframe>
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page').locator('.block-editor-inserter__main-area .block-editor-block-types-list__list-item span:text("Paragraph")').first()
  locator resolved to visible <span data-wp-c16t="true" data-wp-component="Truncate"…>Paragraph</span>
attempting hover action
  waiting for element to be visible and stable
  element is visible and stable
  scrolling into view if needed
  done scrolling
============================================================
at EditorSidebarBlockInserterComponent.selectBlockInserterResult (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts:80:32)
    at EditorPage.addBlockFromInserter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:383:18)
    at EditorPage.addBlockFromSidebar (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:311:3)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:59:24)
```

![image](https://user-images.githubusercontent.com/6549265/213294855-953fc158-a41f-408a-a31f-6cbc03f030b6.png)

**Comment by worldomonation** [comment]
Issue occurred today.

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
  waiting for frameLocator('iframe.is-loaded')
  locator resolved to visible <iframe class="is-loaded" src="https://e2eflowtestingsim…></iframe>
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page').locator('.block-editor-inserter__main-area .block-editor-block-types-list__list-item span:text("Paragraph")').first()
  locator resolved to visible <span data-wp-c16t="true" data-wp-component="Truncate"…>Paragraph</span>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
at EditorSidebarBlockInserterComponent.selectBlockInserterResult (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts:81:17)
    at EditorPage.addBlockFromInserter (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:383:3)
    at EditorPage.addBlockFromSidebar (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:311:3)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:59:24)
```

![image](https://user-images.githubusercontent.com/6549265/219510443-3957897c-e1bd-49c2-8a91-9cf9b07d7720.png)

**Comment by worldomonation** [comment]
This keeps happening. Increasing priority.

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/219780735-029ac793-d05a-4937-bd08-eb7c9bedf004.png)

Uh, that's not good.

**Comment by worldomonation** [comment]
@fullofcaffeine The timeline seems to match up with release of Gutenberg 15.1.x. 

Edit: it looks like the slow loading of the patterns is at least partly to blame here. Even when I ran the test locally in debug mode and stepped through manually, it had difficulty locating the "Paragraph" block entry in the sidebar.

**Comment by worldomonation** [comment]
As commented in https://github.com/Automattic/wp-calypso/issues/73619, anecdotally I haven't seen this happen recently. Closing as resolved.
