### ISSUE TITLE
Flaky E2E: Publish post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72586]
### Spec file

specs/onboarding/ftme__write.ts

### TeamCity ID

9367716

### Logs

```
Error: No published article URL found in response.
at EditorPage.publish (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:661:10)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__write.ts:122:4)
```

**Comment by worldomonation** [comment]
Issue may be related to the restructuring I did in https://github.com/Automattic/wp-calypso/pull/72112.
