### ISSUE TITLE
Flaky E2E: Visit latest post

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72620]
### Spec file

specs/published-content/reader__view.ts

### TeamCity ID

9370484

### Logs

```
page.waitForNavigation: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "networkidle"
  navigated to "https://container-blissful-colden.calypso.live/read/feeds/49495035/posts/3702357429"
============================================================
at ReaderPage.visitPost (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/reader-page.ts:82:14)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/published-content/reader__view.ts:29:3)
```

**Comment by worldomonation** [comment]
Hmm, suspicious. Aother `waitForNavigation` flakiness.
