### ISSUE TITLE
Flaky E2E: EditorPage.waitUntilLoaded

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#72622]
### Spec file

editor__navbar.ts

### TeamCity ID

9370813

### Logs

```
locator.elementHandle: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page')
  waiting for frameLocator('iframe.is-loaded')
  locator resolved to visible <iframe class="is-loaded" src="https://e2eflowtestingsim…></iframe>
  locator resolved to visible <body class="wp-admin wp-core-ui js is-iframed slider-…>…</body>
============================================================
at EditorWelcomeTourComponent.forceDismissWelcomeTour (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts:28:43)
    at EditorPage.waitUntilLoaded (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:160:41)
    at EditorPage.visit (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:143:3)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__navbar.ts:42:3)
```

**Comment by worldomonation** [comment]
Made the flaky issue generic, because the issue identified in the logs affect a bunch of specs that use EditorPage.

**Comment by worldomonation** [comment]
Related issue: 

```
page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
=========================== logs ===========================
waiting for response /.*posts.*/
============================================================
at EditorPage.waitUntilLoaded (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:157:19)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/shared/privacy-testing.ts:54:22)
```

**Comment by worldomonation** [comment]
More occurrences:

```
locator.elementHandle: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page')
  waiting for frameLocator('iframe.is-loaded')
  locator resolved to visible <iframe class="is-loaded" src="https://e2eflowtestingsim…></iframe>
  locator resolved to visible <body class="wp-admin wp-core-ui js is-iframed slider-…>…</body>
============================================================
at EditorWelcomeTourComponent.forceDismissWelcomeTour (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts:28:43)
    at EditorPage.waitUntilLoaded (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:160:41)
    at EditorPage.visit (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:143:3)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__revisions.ts:40:3)
```

**Comment by worldomonation** [comment]
Closing for now as it is completed.
