### ISSUE TITLE
issue in bundler

### ISSUE THREAD

**Issue by ashikkalavadiya** [Automattic/wp-calypso#733]
While creating docker image i got,
```
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at /calypso/server/bundler/bin/bundler.js:41:14
    at Array.forEach (native)
    at minify (/calypso/server/bundler/bin/bundler.js:34:8)
    at /calypso/server/bundler/bin/bundler.js:81:2
    at Compiler.<anonymous> (/calypso/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/calypso/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/calypso/node_modules/webpack/lib/Compiler.js:187:11)
make: *** [build-wpcalypso] Error 1
The command '/bin/sh -c CALYPSO_ENV=wpcalypso make build-wpcalypso &&           CALYPSO_ENV=horizon make build-horizon &&           CALYPSO_ENV=stage make build-stage &&           CALYPSO_ENV=production make build-production &&           chown -R nobody /calypso' returned a non-zero code: 2
```
Though i have commented  line#8 and 9 in Dockerfile for early errors

**Comment by lancewillett** [comment]
Hi ashikkalavadiya — see [troubleshooting](https://github.com/Automattic/wp-calypso/blob/master/docs/troubleshooting.md) for explanations of common issues during setup.

**Comment by stephanethomas** [comment]
@ashikkalavadiya, this `ENOMEM` error was raised because your system couldn't allocate enough memory to build files. I've just ran into this issue as well while running Calypso from its [Vagrant development environment](https://github.com/Automattic/wp-calypso-bootstrap) in production mode (I had to allocate 3072 MB for the virtual machine to make it work).
