### ISSUE TITLE
Flaky E2E: Select WordPress.com Personal plan

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#73450]
### Spec file

specs/onboarding/ftme__sell.ts

### TeamCity ID

9501190

### Logs

```
page.waitForURL: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at SignupPickPlanPage.selectPlan (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/signup/signup-pick-plan-page.ts:46:14)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/ftme__sell.ts:76:21)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/219463070-d1680a01-593c-4772-9340-c62d97938de8.png)

[ftme__sell__select-wordpress-com-personal-plan__1-1.webm](https://user-images.githubusercontent.com/6549265/219463259-c2f1f59e-5bc7-4818-bd45-4eb9aeec177a.webm)

**Comment by worldomonation** [comment]
1/346 runs. 

<img width="1337" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/2f62f442-656f-4de8-8260-42f0de061c56">
