### ISSUE TITLE
Flaky E2E: Append additional content

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#73619]
### Spec file

specs/editor/editor__post-advanced-flow.ts

### TeamCity ID

9521778

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.is-loaded').locator('body.block-editor-page').locator('.block-editor-inserter__main-area .block-editor-block-types-list__list-item span:text("Paragraph")').first()
  locator resolved to <span data-wp-c16t="true" data-wp-component="Truncate"…>Paragraph</span>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
============================================================
at EditorSidebarBlockInserterComponent.selectBlockInserterResult (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts:81:17)
    at EditorPage.addBlockFromInserter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:383:3)
    at EditorPage.addBlockFromSidebar (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:311:3)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:98:24)
```

![image](https://user-images.githubusercontent.com/6549265/220469439-c8ba9199-80dd-4c35-8d3d-a1a438901e44.png)

**Comment by worldomonation** [comment]
Ah, looks like similar issue to https://github.com/Automattic/wp-calypso/issues/72298. The root cause of this is that searching for a common block name such as Paragraph is really taxing since Gutenberg 15.1.x introduced some weird behavior for the search results.

See https://github.com/WordPress/gutenberg/pull/48085 for more information.

**Comment by worldomonation** [comment]
See also: https://github.com/Automattic/wp-calypso/issues/72298

**Comment by worldomonation** [comment]
Frequency should reduce as older branches without the fix (https://github.com/Automattic/wp-calypso/pull/73561) get merged or abandoned.

**Comment by worldomonation** [comment]
Anecdotally, I haven't seen this pop up recently. Closing as resolved.
