### ISSUE TITLE
Flaky E2E: Editor canvas loads

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74009]
### Spec file

fse__temp-smoke-test.ts

### Logs

Related to #73979

```
locator.waitFor: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe.is-loaded[src*="wp-admin/site-editor.php"]').locator('body.block-editor-page').locator('button[aria-label="Open Navigation Sidebar"]') to be visible
============================================================
at FullSiteEditorPage.closeNavSidebar (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:409:36)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__temp-smoke-test.ts:53:28)
    at Promise.then.completed (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
@jeyip Hi, we got reports in p1677742893095889-slack-C02DQP0FP about this step failing.

Could I ask someone to take a look please? Thank!

**Comment by worldomonation** [comment]
I ended up creating a proposed fix for it. https://github.com/Automattic/wp-calypso/pull/74010.

**Comment by jeyip** [comment]
Taking a look
