### ISSUE TITLE
Flaky E2E: Create revisions

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74682]
### Spec file

test/e2e/specs/editor/editor__revisions.ts

### TeamCity ID

9689703

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('body.block-editor-page').locator('div.block-editor-default-block-appender')
============================================================
at EditorGutenbergComponent.enterText (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-gutenberg-component.ts:99:28)
    at EditorPage.enterText (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:267:3)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__revisions.ts:44:3)
```

**Comment by worldomonation** [comment]
This affects only AT sites.

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/226493166-ef9451c4-bcd0-48dc-9e97-d66128b90e0f.png)

**Comment by worldomonation** [comment]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/6549265/233012729-3e95b04b-2437-426c-8270-1aef6c999b2c.png">

https://teamcity.a8c.com/test/-3863774952284162593?currentProjectId=calypso_WPComTests&expandTestHistoryChartSection=true

**Comment by worldomonation** [comment]
Not a priority now given the low intermittence.

<img width="1351" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/04c37ef4-f2f7-4590-b791-83941681a8fd">
