### ISSUE TITLE
Flaky E2E: Editor is shown

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74925]
### Spec file

 specs/editor/editor__post-advanced-flow.ts

### TeamCity ID

9725483

### Logs

```
locator.elementHandle: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('body.block-editor-page')
============================================================
at EditorWelcomeTourComponent.forceToggleWelcomeTour (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts:29:43)
    at EditorWelcomeTourComponent.forceDismissWelcomeTour (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-welcome-tour-component.ts:75:14)
    at EditorPage.waitUntilLoaded (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:171:41)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:95:4)
```

**Comment by worldomonation** [comment]
This failure occurs because the editor is targetting `atomic` when the [spec file is initially called](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/editor/editor__post-advanced-flow.ts#L50).

However, in the `Editor is shown` step, the editor that loads has - inexplicably - an iframe.

**Comment by worldomonation** [comment]
The effort to un-iframe the editor in https://github.com/Automattic/wp-calypso/pull/74384 should help resolve this issue by standardizing the behavior between Atomic and Simple editors.

**Comment by worldomonation** [comment]
> The effort to un-iframe the editor in #74384 should help resolve this issue by standardizing the behavior between Atomic and Simple editors.

Last I know is that the un-iframing of editor now only concerns the Site Editor.
