### ISSUE TITLE
Failed E2E: Navigate to Full Site Editor

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#74999]
### Spec file

specs/fse/fse__temp-smoke-test.ts

### TeamCity ID

9725510

### Logs

```
page.waitForNavigation: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at SidebarComponent.navigate (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:83:15)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__temp-smoke-test.ts:44:3)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/228092556-6f460277-9106-4a73-a107-d4c8470a4c53.png)

**Comment by worldomonation** [comment]
Root cause being that the test user is using a non-FSE theme.
