### ISSUE TITLE
Flaky E2E: Like the comment

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75089]
### Spec file

 specs/published-content/likes__comment.ts

### TeamCity ID

9734441

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe[name^="like-comment-frame"]:below(:text("19 Small Donkeys Scare Equally"))').locator('a:text-is("Like"):visible')
============================================================
at CommentsComponent.like (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/comments-component.ts:90:20)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/published-content/likes__comment.ts:84:4)
```

**Comment by worldomonation** [comment]
Brother of https://github.com/Automattic/wp-calypso/issues/74547.

**Comment by worldomonation** [comment]
My changes in https://github.com/Automattic/wp-calypso/pull/74591 made the issue worse.
