### ISSUE TITLE
Flaky E2E: Insert Dynamic HR block

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75092]
### Spec file

specs/blocks/blocks__coblocks__blocks.ts

### TeamCity ID

9749250

### Logs

```
locator.hover: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('body.block-editor-page').locator('.block-editor-inserter__main-area .block-editor-block-types-list__list-item span:text("Dynamic HR")').first()
============================================================
at EditorSidebarBlockInserterComponent.selectBlockInserterResult (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-sidebar-block-inserter-component.ts:80:32)
    at EditorPage.addBlockFromInserter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:389:18)
    at EditorPage.addBlockFromSidebar (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:312:3)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/blocks__coblocks__blocks.ts:71:3)
```

**Comment by worldomonation** [comment]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/6549265/228662783-9e9a2b24-1aa2-4074-bdc1-b7b55890be6f.png">
