### ISSUE TITLE
Flaky E2E: Enter empty search keyword

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75459]
### Spec file

specs/support/support__home.ts

### TeamCity ID

9805706

### Logs

```
page.waitForResponse: Timeout 10000ms exceeded while waiting for event "response"
at SupportComponent.search (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/support-component.ts:167:14)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/support/support__home.ts:68:27)
    at Promise.then.completed (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by cpapazoglou** [comment]
It seems to me that it’s related to database. Code hasn’t changed for a while, the query triggered 

`gpr SELECT SQL_CALC_FOUND_ROWS  wp_142208464_posts.* FROM wp_142208464_posts  WHERE (((wp_142208464_posts.post_title LIKE '%+++%') OR (wp_142208464_posts.post_excerpt LIKE '%+++%') OR (wp_142208464_posts.post_content LIKE '%+++%')))  AND wp_142208464_posts.post_type = 'topic' AND ((wp_142208464_posts.post_status = 'publish'))  ORDER BY wp_142208464_posts.ID DESC LIMIT 0, 5`

SHOULD be performant and is well formatted trying to escape doing expensive operations by NOT using SQL_CALC_FOUND_ROWS. While switching to use SQL_CALC_FOUND_ROWS seems more performant in my tests and will resolve the issue:
- I don’t know why it’s more performant
- Doesn’t seem the correct thing to do to resolve the issue
Thus, I would wait for [#opers](p1681122228882779-slack-C02AVAR9B) feedback

**Comment by worldomonation** [comment]
Looks like the issue has resolved itself.

**Simple**
<img width="1343" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/365a94e5-7cb1-4270-b8be-c9a71b42d27a">

**Atomic**
<img width="1342" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/821c60b6-9f1e-496a-9b09-f7dc154945c6">

Slack threads:
- p1681105318897349-slack-C03N25JPCE4
- p1681122228882779-slack-C02AVAR9B

**Comment by worldomonation** [comment]
Thanks for the initial investigation @cpapazoglou - your tenacy in looking for an answer is amazing! 
I'm going to close this issue for now as the behavior has gone back to what it is expected to be, though I'm interested in moving this spec to a component test at some point.
