### ISSUE TITLE
Flaky E2E: Select and view details of a theme starting with Twenty Twen

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75531]
### Spec file

specs/appearance/theme__details-preview-activate.ts

### TeamCity ID

9813045

### Logs

```
Error: No theme shown on page that match name: Twenty Twen.
at ThemesPage.select (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/themes-page.ts:90:10)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/appearance/theme__details-preview-activate.ts:60:25)
```

**Comment by worldomonation** [comment]
This is not limited to Twenty Twenty; the spec at `specs/appearance/theme__popover-preview.ts` which searches for Twenty Seventeen also encounters this issue.

![image](https://user-images.githubusercontent.com/6549265/231097778-b5ea490f-0255-4614-ad32-c02e9e7182b2.png)

**Comment by worldomonation** [comment]
Closing due to low intermittence.

<img width="1346" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/7f6a364b-2ae1-4c8b-ada1-f5be4aeca42d">
