### ISSUE TITLE
Flaky E2E: Ensure published post contains additional content

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75670]
### Spec file

test/e2e/specs/editor/editor__post-advanced-flow.ts:121:4

### TeamCity ID

9829544

### Logs

```
page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('p:text("Updated post content")') to be visible
============================================================
at Function.validatePublishedContent (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/paragraph-block.ts:46:15)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-advanced-flow.ts:121:4)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/231670909-b930174f-c55d-4ed0-a5fe-0dfdfcca20b6.png)

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/231670964-525bea54-d8ba-4eaf-a886-aa7b3f92d292.png)

**Comment by worldomonation** [comment]
The issue is that after the updated post content is posted, the changes haven't propagated to the post when it is loaded. 

Thus when the post is loaded the old content (prior to the edits) are shown.

**Comment by worldomonation** [comment]
https://teamcity.a8c.com/test/4220047049296829121?currentProjectId=calypso_WPComTests
