### ISSUE TITLE
Flaky E2E: Upload image (Gutenberg Edge)

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75748]
### Spec file

specs/blocks/blocks__coblocks__extensions__cover-styles.ts

### TeamCity ID

9837866

### Logs

```
elementHandle.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('img:not([src^="blob:"])') to be visible
============================================================
at CoverBlock.waitUntilUploaded (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/image-block.ts:56:15)
    at CoverBlock.upload (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/image-block.ts:70:14)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/blocks__coblocks__extensions__cover-styles.ts:61:3)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/231963542-da738a06-29b8-469c-877f-1f74b08504e8.png)

**Comment by worldomonation** [comment]
Looks like the image is being uploaded fine, but maybe the element string pattern changed.
