### ISSUE TITLE
Flaky E2E: Select "Footer"

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75812]
### Spec file

specs/onboarding/setup__site-assembler.ts

### TeamCity ID

9845583

### Logs

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.block-renderer').first()
  locator resolved to <div class="block-renderer">…</div>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #4
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #5
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #6
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #7
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #8
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #9
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #10
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #11
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #12
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #13
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #14
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #15
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #16
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #17
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #18
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #19
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <li class="pattern-large-preview__pattern pattern-la…>…</li> intercepts pointer events
retrying click action, attempt #20
  waiting 500ms
============================================================
at SiteAssemblerFlow.selectFooter (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/flows/site-assembler-flow.ts:47:16)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__site-assembler.ts:68:4)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/232389029-9706e56d-5fb0-4bb6-85ca-d7cfca0fff6b.png)

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/232389191-6b1e0906-7acb-4f93-9964-f41653038f4c.png)

**Comment by worldomonation** [comment]
@okmttdhr Just a heads up that it still looks like the test is still flaking out sometimes at the `Select "Footer"` step.

I will take a look at this today.

**Comment by worldomonation** [comment]
As far as I can tell, this has been a success:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/6549265/233880464-1a1ede78-6b99-4cbf-9725-5fcbd3f2c69b.png">
