### ISSUE TITLE
Flaky E2E: Navigate to Appearance > Widgets

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#75816]
### Spec file

specs/appearance/widgets__legacy-visibility.ts

### TeamCity ID

9845750

### Logs

```
page.waitForNavigation: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
  navigated to "https://e2eflowtestinggutenbergsimpleedge.wordpress.com/wp-admin/widgets.php"
============================================================
at SidebarComponent.navigate (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:83:15)
    at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/appearance/widgets__legacy-visibility.ts:45:4)
```

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/232419580-a0bc391b-6b77-4de0-9a82-c5696ddc25fb.png)
