### ISSUE TITLE
E2E: add basic coverage of the `/me` endpoint.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#76266]
### Details

After an issue in production affecting the `/me` endpoint, I brought up that it will be good return for investment to implement a basic sanity check of the `/me` endpoint.

Slack: p1682461410082299-slack-C02FMH4G8
Issue: https://github.com/Automattic/wp-calypso/issues/76250
PR that caused issue: https://github.com/Automattic/wp-calypso/pull/76167

### Checklist

- [x] Implement a basic flow that covers the `/me` endpoint.
- [x] Run it for the `calypso-pr` group.

**Comment by worldomonation** [comment]
Closing as implemented by https://github.com/Automattic/wp-calypso/pull/78268.

**Comment by worldomonation** [comment]
Some specs in desktop mode is running into this:

```
locator.click: Error: strict mode violation: getByRole('link', { name: 'Apps' }) resolved to 2 elements:
1) <a href="/me/get-apps" class="sidebar__menu-link">…</a> aka getByRole('link', { name: 'Apps', exact: true })
    2) <a href="/me/security/connected-applications">…</a> aka getByRole('link', { name: 'Connected Apps You currently have 1 connected application. .' })
=========================== logs ===========================
waiting for getByRole('link', { name: 'Apps' })
============================================================
    at /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/me/me__smoke.ts:47:53
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-each/build/bind.js:79:13)
    at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```
