### ISSUE TITLE
Flaky E2E: Land in checkout cart

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#76264]
### Spec file

specs/onboarding/setup__videopress.ts

### TeamCity ID

9900972

### Logs

Likely caused by https://github.com/Automattic/wp-calypso/pull/76157.

```
locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('.wp-checkout-order-summary__total-price') to be visible
============================================================
at CartCheckoutPage.getCheckoutTotalAmount (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/cart-checkout-page.ts:211:28)
    at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__videopress.ts:85:47)
    at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
Appears to be fixed by https://github.com/Automattic/wp-calypso/pull/76492.

Incidence is 0 since April 27.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6549265/236787711-cf13de9b-6332-40e0-8267-2d6b16798034.png">
