### ISSUE TITLE
Flaky E2E: Navigate to Appearance > Widgets

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#76592]
### Spec file

specs/appearance/widgets__legacy-visibility.ts

### TeamCity ID

9953412

### Logs

```
page.goto: Timeout 10000ms exceeded.
=========================== logs ===========================
navigating to "https://e2eflowtesting1472219724640.wordpress.com/wp-admin/widgets.php", waiting until "load"
============================================================
at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/appearance/widgets__legacy-visibility.ts:43:15)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
Very high failure rate.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/6549265/236237472-862444f1-534c-49bf-9699-14fc92c153e6.png">

https://teamcity.a8c.com/test/4275866801021569722?currentProjectId=calypso_WPComTests&expandTestHistoryChartSection=true&branch=

**Comment by worldomonation** [comment]
https://teamcity.a8c.com/test/4275866801021569722?currentProjectId=calypso_WPComTests&expandTestHistoryChartSection=true&branch=

**Comment by worldomonation** [comment]
![image](https://user-images.githubusercontent.com/6549265/236237673-3831b5e9-43be-447b-9d74-5f7eaa100d76.png)

**Comment by worldomonation** [comment]
Intermittence rate is getting worse. 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/6549265/236975609-1bfda7ed-9481-4b77-b9ed-eeeafc308002.png">
