### ISSUE TITLE
Flaky E2E: Enter empty search keyword and expect no results to be shown

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#76916]
### Spec file

pecs/support/support__popover-invalid.ts

### TeamCity ID

10011482

### Logs

![image](https://github.com/Automattic/wp-calypso/assets/6549265/6abc5ecc-43e4-42f2-85dc-78ce184075b3)

```
page.waitForSelector: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator(':has-text("Sorry, there were no matches.")') to be visible
============================================================
at SupportComponent.noResultsShown (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/support-component.ts:130:19)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/support/support__popover-invalid.ts:49:27)
```

**Comment by worldomonation** [comment]
Permafailing and https://github.com/Automattic/wp-calypso/pull/76866 did not help.
