### ISSUE TITLE
Flaky E2E: Buy suggested domain

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#77007]
### Spec file

specs/domain-upsell/domain-upsell__my-home.ts

### Logs

![image](https://github.com/Automattic/wp-calypso/assets/6549265/189a32f7-98dd-4e25-9abe-8a85a941e34b)

```
page.waitForNavigation: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
============================================================
at MyHomePage.clickBuySuggestedDomain (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/my-home-page.ts:87:14)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/domain-upsell/domain-upsell__my-home.ts:54:20)
    at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/97cfdb39-48e1-4739-874a-0944359c6936)

**Comment by worldomonation** [comment]
Still happening more often than I'd like.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/82cb748f-4642-48b9-a491-da52aa2d0cbd)

**Comment by worldomonation** [comment]
Picking up this item as it keeps flaking out, making discovery of actual issues difficult.

**Comment by worldomonation** [comment]
<img width="1023" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/1c2228f7-fcfb-4f4f-bfc4-10854cd3e90a">
