### ISSUE TITLE
Permafailing E2E: View the Reader stream

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#77993]
### Spec file

specs/published-content/reader__view.ts

### TeamCity ID

10160191

### Logs

```
page.getAttribute: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('.reader-visit-link')
============================================================
at ReaderPage.siteOfLatestPost (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/reader-page.ts:49:32)
    at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/published-content/reader__view.ts:38:45)
```

**Comment by worldomonation** [comment]
<img width="1326" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/edc2ab54-df8b-47e4-9c23-44878c376f18">

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/acec69ca-744f-4681-9d09-47677f4c9732)

**Comment by worldomonation** [comment]
The user that this test user was subscribed to (and the site from which the content is expected to be present) has been deleted, which might explain the issue.
