### ISSUE TITLE
Flaky E2E: Activate account

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78159]
### Spec file

test/e2e/specs/onboarding/setup__videopress.ts

### TeamCity ID

10198245

### Logs

```
page.goto: net::ERR_ABORTED at https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fsignup.wordpress.com%2Factivate%2F47c021d15a444e11&sr=1&signature=ff4f6441709fcd07720b2044fddd38c2&user=236401502&_e=eyJlcnJvciI6bnVsbCwiYmxvZ19pZCI6NTgzNjA4NiwiYmxvZ19sYW5nIjoiZW4iLCJzaXRlX2lkX2xhYmVsIjoid3Bjb20iLCJfdWkiOjIzNjQwMTUwMiwibG9jYWxlIjoiZW4iLCJjdXJyZW5jeSI6IlVTRCIsImNvdW50cnlfY29kZV9zaWdudXAiOiJVUyIsInNpZ251cF9mbG93X25hbWUiOiJ2aWRlb3ByZXNzLWFjY291bnQtdmlkZW9wcmVzcyIsImVtYWlsX2RvbWFpbiI6IjZvYjI0cGduLm1haWxvc2F1ci5uZXQiLCJkYXRlX3NlbnQiOiIyMDIzLTA2LTEzIiwiZW1haWxfaWQiOiI0NjkwYjYzODNkNjgxOTM1MWEzZjJjYWVhNTc0NTVkZiIsImVtYWlsX25hbWUiOiJkZWx0YV9hY3RpdmF0aW9uIiwidGVtcGxhdGUiOiJhY3RpdmF0aW9uIiwibGlua19kZXNjIjoiIiwiYW5jaG9yX3RleHQiOiJDb25maXJtIHlvdXIgZW1haWwiLCJfZHIiOm51bGwsIl9kbCI6IlwvcmVzdFwvdjEuMVwvdXNlcnNcL25ldz9odHRwX2VudmVsb3BlPTEiLCJfdXQiOiJ3cGNvbTp1c2VyX2lkIiwiX3VsIjoiZTJlZmxvd3Rlc3Rpbmd2aWRlb3ByZXNzb25ib2FyZGluZzE2ODY2NzI2NTA1MTg2NTEiLCJfZW4iOiJ3cGNvbV9lbWFpbF9jbGljayIsIl90cyI6MTY4NjY3MjY1Mzc4MiwiYnJvd3Nlcl90eXBlIjoicGhwLWFnZW50IiwiX2F1YSI6IndwY29tLXRyYWNrcy1jbGllbnQtdjAuMyIsImJsb2dfdHoiOiIwIiwidXNlcl9sYW5nIjoiZW4ifQ=&_z=z
=========================== logs ===========================
navigating to "https://public-api.wordpress.com/bar/?stat=groovemails-events&bin=wpcom_email_click&redirect_to=https%3A%2F%2Fsignup.wordpress.com%2Factivate%2F47c021d15a444e11&sr=1&signature=ff4f6441709fcd07720b2044fddd38c2&user=236401502&_e=eyJlcnJvciI6bnVsbCwiYmxvZ19pZCI6NTgzNjA4NiwiYmxvZ19sYW5nIjoiZW4iLCJzaXRlX2lkX2xhYmVsIjoid3Bjb20iLCJfdWkiOjIzNjQwMTUwMiwibG9jYWxlIjoiZW4iLCJjdXJyZW5jeSI6IlVTRCIsImNvdW50cnlfY29kZV9zaWdudXAiOiJVUyIsInNpZ251cF9mbG93X25hbWUiOiJ2aWRlb3ByZXNzLWFjY291bnQtdmlkZW9wcmVzcyIsImVtYWlsX2RvbWFpbiI6IjZvYjI0cGduLm1haWxvc2F1ci5uZXQiLCJkYXRlX3NlbnQiOiIyMDIzLTA2LTEzIiwiZW1haWxfaWQiOiI0NjkwYjYzODNkNjgxOTM1MWEzZjJjYWVhNTc0NTVkZiIsImVtYWlsX25hbWUiOiJkZWx0YV9hY3RpdmF0aW9uIiwidGVtcGxhdGUiOiJhY3RpdmF0aW9uIiwibGlua19kZXNjIjoiIiwiYW5jaG9yX3RleHQiOiJDb25maXJtIHlvdXIgZW1haWwiLCJfZHIiOm51bGwsIl9kbCI6IlwvcmVzdFwvdjEuMVwvdXNlcnNcL25ldz9odHRwX2VudmVsb3BlPTEiLCJfdXQiOiJ3cGNvbTp1c2VyX2lkIiwiX3VsIjoiZTJlZmxvd3Rlc3Rpbmd2aWRlb3ByZXNzb25ib2FyZGluZzE2ODY2NzI2NTA1MTg2NTEiLCJfZW4iOiJ3cGNvbV9lbWFpbF9jbGljayIsIl90cyI6MTY4NjY3MjY1Mzc4MiwiYnJvd3Nlcl90eXBlIjoicGhwLWFnZW50IiwiX2F1YSI6IndwY29tLXRyYWNrcy1jbGllbnQtdjAuMyIsImJsb2dfdHoiOiIwIiwidXNlcl9sYW5nIjoiZW4ifQ=&_z=z", waiting until "load"
============================================================
at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/onboarding/setup__videopress.ts:126:15)
    at Promise.then.completed (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:391:28)
    at callAsyncCircusFn (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:316:10)
    at _callCircusTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:218:40)
    at _runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:155:3)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:66:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at _runTestsForDescribeBlock (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:60:9)
    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:170:21)
    at jestAdapter (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:82:19)
    at runTestInternal (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:389:16)
    at runTest (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:475:34)
    at Object.worker (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:133:12)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/569e5238-f95d-4637-8f59-1406a432a3cb)

**Comment by worldomonation** [comment]
https://github.com/Automattic/wp-calypso/assets/6549265/5a55960b-2e0c-4420-b5d2-48d50685647b

**Comment by worldomonation** [comment]
<img width="1545" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/cb41ea82-b1e4-406f-b0b2-ca0d27a93526">
