### ISSUE TITLE
Flaky E2E: Navigate to Full Site Editor

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78191]
### Spec file

test/e2e/specs/fse/fse__temp-smoke-test.ts

### TeamCity ID

10204756

### Logs

<img width="1022" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/9511b96d-d8c7-436f-9b02-f32f799f41bc">

```
page.waitForNavigation: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for navigation until "load"
  navigated to "https://e2eflowtestingsiteeditorsimple282698206.wordpress.com/wp-admin/site-editor.php"
  "domcontentloaded" event fired
============================================================
at SidebarComponent.navigate (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/sidebar-component.ts:83:15)
    at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__temp-smoke-test.ts:76:3)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/d104e9c7-fb48-4485-aacb-03d1ffc45c00)

**Comment by worldomonation** [comment]
<img width="1016" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/c797e563-dc7b-4492-8082-197f00ded74a">

**Comment by worldomonation** [comment]
https://github.com/Automattic/wp-calypso/assets/6549265/cdd4230b-e938-468c-8597-81f612d6f38e
