### ISSUE TITLE
Flaky E2E: Launch preview

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#78975]
### Spec file

specs/editor/editor__post-basic-flow.ts

### TeamCity ID

10326391

### Logs

![image](https://github.com/Automattic/wp-calypso/assets/6549265/c28889a3-3a96-47c1-bd50-49c5b6b76d9c)

```
======= Failed test run #1 ==========
  locator.getAttribute: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').locator('.interface-navigable-region[class*="header"] :text("View"):visible')
  ============================================================
  at EditorToolbarComponent.targetIsOpen (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:101:33)
      at EditorToolbarComponent.openDesktopPreviewMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:200:12)
      at EditorToolbarComponent.openDesktopPreview (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:177:3)
      at EditorPage.previewAsDesktop (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:743:3)
      at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:92:5)
======= Failed test run #2 ==========
  locator.getAttribute: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').locator('.interface-navigable-region[class*="header"] :text("View"):visible')
  ============================================================
  at EditorToolbarComponent.targetIsOpen (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:101:33)
      at EditorToolbarComponent.openDesktopPreviewMenu (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:200:12)
      at EditorToolbarComponent.openDesktopPreview (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-toolbar-component.ts:177:3)
      at EditorPage.previewAsDesktop (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:743:3)
      at Object.<anonymous> (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__post-basic-flow.ts:92:5)
```

**Comment by worldomonation** [comment]
![image](https://github.com/Automattic/wp-calypso/assets/6549265/16559203-45ae-4b8e-9c5f-b059fd606fdf)

[Uploading editor__post-basic-flow__launch-preview__2023-07-05_01-03-36__1-1.webm…]()
