### ISSUE TITLE
Flaky E2E: Jetpack Instant Search (Atomic: wp-beta): Navigate to site homepage

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81126]
### Spec file

specs/search/search__jetpack-instant.ts

### TeamCity ID

10672855

### Logs

```
======= Failed test run #1 ==========
  page.goto: Timeout 20000ms exceeded.
  =========================== logs ===========================
  navigating to "https://jetpackedgewpbeta.wpcomstaging.com/", waiting until "load"
  ============================================================
  at Object.goto (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/search/search__jetpack-instant.ts:76:14)
      at Promise.then.completed (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:300:28)
      at callAsyncCircusFn (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:233:10)
      at _callCircusTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:315:40)
      at _runTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:251:3)
      at _runTestsForDescribeBlock (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:125:9)
      at _runTestsForDescribeBlock (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:120:9)
      at run (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:70:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
      at Object.worker (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:106:12)
======= Failed test run #2 ==========
  page.goto: Timeout 20000ms exceeded.
  =========================== logs ===========================
  navigating to "https://jetpackedgewpbeta.wpcomstaging.com/", waiting until "load"
  ============================================================
  at Object.goto (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/search/search__jetpack-instant.ts:76:14)
      at Promise.then.completed (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:300:28)
      at callAsyncCircusFn (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:233:10)
      at _callCircusTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:315:40)
      at _runTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:251:3)
      at _runTestsForDescribeBlock (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:125:9)
      at _runTestsForDescribeBlock (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:120:9)
      at run (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:70:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
```

Related to: https://github.com/Automattic/wp-calypso/pull/80991

**Comment by worldomonation** [comment]
Seems to be failing at this step both tries:

![image](https://github.com/Automattic/wp-calypso/assets/6549265/39781efc-c1dd-4a95-bbc6-0c89bd3f1e24)
