### ISSUE TITLE
Flaky E2E: Jetpack Instant Search (Atomic: default): Enter search term and launch search modal

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81343]
### Spec file

specs/search/search__jetpack-instant.ts

### TeamCity ID

10716610

### Logs

```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('dialog', { name: 'Search results' }).getByRole('heading', { name: 'Searching…', includeHidden: true }) to be visible
  ============================================================
  at JetpackInstantSearchModalComponent.waitFor [as expectAndWaitForSearch] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/jetpack-instant-search-modal-component.ts:77:41)
      at Object.expectAndWaitForSearch (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/search/search__jetpack-instant.ts:107:45)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('dialog', { name: 'Search results' }).getByRole('heading', { name: 'Searching…', includeHidden: true }) to be visible
  ============================================================
  at JetpackInstantSearchModalComponent.waitFor [as expectAndWaitForSearch] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/jetpack-instant-search-modal-component.ts:77:41)
      at Object.expectAndWaitForSearch (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/search/search__jetpack-instant.ts:107:45)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/c3103687-9053-410a-b80e-da6e7bf7b1f1)

**Comment by worldomonation** [comment]
@dpasque Still seeing some flakiness here that started on August 30th. 

I can take a look too if you'd like.

**Comment by dpasque** [comment]
So... I took a quick peek at the failing tests today, and for whatever reason, on the sites that are failing, one of the top level DOM elements, `.wp-site-blocks`, has `aria-hidden` set to `true`. I have _no_ idea why that would be the case for only some of our sites. 😅 That seems like a bug?

We should see if we can figure out how to correct that. Otherwise, we can set the selector to allow hidden elements.
