### ISSUE TITLE
Flaky E2E: Jetpack Grow (Atomic: default): Add and configure blocks in the editor: Business Hours: Add the block from the sidebar

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#81763]
### TeamCity ID

10799713

### Logs

```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').frameLocator('iframe[name="editor-canvas"]').locator('.editor-styles-wrapper').locator(':is(div[aria-label="Block: Business Hours"].is-selected, div[aria-label="Block: Business Hours"].has-child-selected)') to be visible
  ============================================================
  at EditorGutenbergComponent.waitFor [as getSelectedBlockElementHandle] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-gutenberg-component.ts:153:17)
      at EditorPage.addBlockFromSidebar (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:282:23)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:54:26)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').frameLocator('iframe[name="editor-canvas"]').locator('.editor-styles-wrapper').locator(':is(div[aria-label="Block: Business Hours"].is-selected, div[aria-label="Block: Business Hours"].has-child-selected)') to be visible
  ============================================================
  at EditorGutenbergComponent.waitFor [as getSelectedBlockElementHandle] (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-gutenberg-component.ts:153:17)
      at EditorPage.addBlockFromSidebar (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:282:23)
      at Object.<anonymous> (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:54:26)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/95a36880-576d-420a-8120-8ebfa3479f0c)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/baa804a3-a959-4c46-954c-5a96662fe881)

**Comment by worldomonation** [comment]
@jeherve It seems the Business Hours block changed appearance on AT? 

What it used to be on the left, what it is now on Jetpack AT sites on the right:
![image](https://github.com/Automattic/wp-calypso/assets/6549265/688f12e8-bd8a-4118-a493-ccae8034e867)

**Comment by jeherve** [comment]
@monsieur-z We seem to be running into a problem similar to the one you fixed in https://github.com/Automattic/jetpack/pull/33090. Do you think you could take a look?

**Comment by worldomonation** [comment]
It looks like the changes were reverted, because the step is no longer failing.

<img width="1343" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/5441752c-a3f0-477b-83d0-21d21759da25">
