### ISSUE TITLE
Flaky E2E: Configure the block (Related Posts block)

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82071]
### Spec file

specs/blocks/blocks__jetpack-other.ts

### Logs

<img width="1566" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/2a8b485d-99ff-4991-a830-31cef312c6d8">

![image](https://github.com/Automattic/wp-calypso/assets/6549265/40def559-6ffd-4802-a46e-b1152894f62d)

```
======= Failed test run #1 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)
======= Failed test run #2 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)
```

**Comment by worldomonation** [comment]
Duplicated by newer issue https://github.com/Automattic/wp-calypso/issues/82072.
