### ISSUE TITLE
Flaky E2E: Other Jetpack Blocks (Atomic: wp-previous): Add and configure blocks in the editor: Related Posts: Configure the block

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82072]
### Spec file

specs/blocks/blocks__jetpack-other.ts

### Logs

```
======= Failed test run #1 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)
======= Failed test run #2 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)
```
![image](https://github.com/Automattic/wp-calypso/assets/6549265/dbdf8766-a682-4d67-9d00-7526a9de844d)

**Comment by worldomonation** [comment]
Turns out on a bunch of test sites, the Related Posts feature had to be activated in the editor as well.

<img width="881" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/8d4ebb3c-a49f-4229-8e2c-82e1e095b2e5">

**Comment by worldomonation** [comment]
After enabling the feature for all sites that were affected, I think we are in a good state.

**Comment by fullofcaffeine** [comment]
FYI, found the same issue in the Gutenberg test sites. I already activated the block for them, too. I'm curious on why that's needed now, though. 🤔 Thanks for creating this issue and documenting it in the failed test!
