### ISSUE TITLE
Flaky E2E: Basic Post Flow (Atomic: private): Start a new page

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82074]
### Spec file

specs/editor/editor__page-basic-flow.ts

### Logs

<img width="1503" alt="image" src="https://github.com/Automattic/wp-calypso/assets/6549265/4a307dcf-50db-492f-8d32-dda1f70eb5a5">

```
======= Failed test run #1 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('link', { name: /(Add new|Start a) page/ })
    locator resolved to <a class="button pages__add-page is-compact is-prim…>Add new page</a>
  attempting click action
    waiting for element to be visible, enabled and stable
    element is visible, enabled and stable
    scrolling into view if needed
    done scrolling
    performing click action
  ============================================================
  at PagesPage.click [as addNewPage] (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/pages-page.ts:35:70)
      at Object.addNewPage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__page-basic-flow.ts:56:19)
      at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:298:28)
      at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:231:10)
      at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:316:40)
      at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:252:3)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:126:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:121:9)
      at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:71:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
      at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:106:12)
======= Failed test run #2 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for getByRole('link', { name: /(Add new|Start a) page/ })
    locator resolved to <a class="button pages__add-page is-compact is-prim…>Add new page</a>
  attempting click action
    waiting for element to be visible, enabled and stable
    element is visible, enabled and stable
    scrolling into view if needed
    done scrolling
    performing click action
  ============================================================
  at PagesPage.click [as addNewPage] (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/pages-page.ts:35:70)
      at Object.addNewPage (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/editor/editor__page-basic-flow.ts:56:19)
      at Promise.then.completed (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:298:28)
      at callAsyncCircusFn (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:231:10)
      at _callCircusTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:316:40)
      at _runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:252:3)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:126:9)
      at _runTestsForDescribeBlock (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:121:9)
      at run (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:71:3)
      at runAndTransformResultsToJestFormat (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
      at jestAdapter (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
      at runTestInternal (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
      at runTest (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
      at Object.worker (/home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:106:12)
```

Related to: https://github.com/Automattic/wp-calypso/issues/80730

**Comment by worldomonation** [comment]
[editor__page-basic-flow__start-a-new-page__atomic--private__1-1.webm](https://github.com/Automattic/wp-calypso/assets/6549265/9a6c7901-c754-4b2d-8623-714f7e5e92c0)

**Comment by worldomonation** [comment]
This one seems a bit tricky; the Calypso Pages page is loading, and the `Add new page` button is indeed being clicked on, but the redirect seems to be either timing out or the editor simply doesn't load.

**Comment by worldomonation** [comment]
Possibly related to https://github.com/Automattic/wp-calypso/issues/82497.

**Comment by dpasque** [comment]
This got way better as we scaled the concurrency down. There's probably some stabilization that could be done here, but it's lower priority. Moving to backlog and lowering priority.
