### ISSUE TITLE
Flaky E2E: Stabilize the "jetpack-other" specs.

### ISSUE THREAD

**Issue by dpasque** [Automattic/wp-calypso#82210]
### Spec file

blocks__jetpack-other.ts

### Logs

There are few failures I've seen over recent simple/atomic runs. We should make sure they are either one-offs and have been fixed, or have been stabilized.

Blocks that have failed:
- Related Posts
- Maps

### Related posts logs:
```
======= Failed test run #1 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)
======= Failed test run #2 ==========
  locator.click: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').getByLabel('Display headline')
  ============================================================
  at RelatedPostsFlow.click [as configure] (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/related-posts.ts:43:56)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:7)

```

### Map log:
```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').locator('.components-popover').getByRole('listbox') to be visible
  ============================================================
  at MapFlow.waitFor [as configure] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/map.ts:41:78)
      at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:71:7)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').locator('.components-popover').getByRole('listbox') to be visible
  ============================================================
  at MapFlow.waitFor [as configure] (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/map.ts:41:78)
      at Object.<anonymous> (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:71:7)
```

**Comment by worldomonation** [comment]
I don't think these specs are failing now, aside from the Starting new post related failures documented in https://github.com/Automattic/wp-calypso/issues/82497 and https://github.com/Automattic/wp-calypso/issues/82074.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/0688932c-ab30-45e5-a070-f473cb3db364)

**Comment by worldomonation** [comment]
Closed as done, for now.
