### ISSUE TITLE
Flaky E2E: Configure the block (Jetpack Forms)

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82530]
### Spec file

specs/blocks/blocks__jetpack-forms.ts

### TeamCity ID

10919898

### Logs

```
locator.fill: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('iframe[src*="calypsoify"]').locator('body.block-editor-page').locator('#block-e36bbc78-94fc-4cf8-ad69-c9e7b3a49472').getByRole('textbox', { name: 'Ask Jetpack AI to create your form' })
============================================================
at FormAiFlow.fill [as configure] (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/blocks/block-flows/form-ai.ts:49:29)
    at Object.configure (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:75:23)
    at Promise.then.completed (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:298:28)
    at callAsyncCircusFn (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:316:40)
    at _runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:121:9)
    at _runTestsForDescribeBlock (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:121:9)
    at run (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/node_modules/jest-runner/build/testWorker.js:106:12)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/fe982836-ceb5-4b4f-a5ba-1e79e8bd4204)

Related to: https://github.com/Automattic/wp-calypso/issues/80730

**Comment by worldomonation** [comment]
This seems to be failing more than passing.

@dpasque, I'm thinking the following - if you can't stabilize this with a couple of hours, let's just remove it. AI form generation is likely going to shift around all the time, so it seems futile to make specs for an ever-changing feature.

**Comment by dpasque** [comment]
I'm untangling two different failures here:

First, it looks like this test is flaky on mobile. That's the main fix that needs to be investigated and dealt with.

Secondly, there were a few desktop failures in the past few days, but if you look at the artifacts, there's actually a bug -- there are like 4 different AI input fields! 😱 But, this is now consistently fixed.

![Screenshot 2023-10-03 at 1 15 01 PM](https://github.com/Automattic/wp-calypso/assets/26772342/ce99ad04-cebe-429b-b8ba-660a87ddb700)

I'm pretty sure though that is related to the "we are loading JS 10 times + concatenation" bug that was recently reverted/fixed on the Jetpack deploy, as it overlaps with that time window.

So, I will focus the rest of this issue investigation/fix on the mobile failure. 👍

**Comment by dpasque** [comment]
Oh, the mobile issue is easy! It looks like the AI input field on mobile moved from below the block to the top toolbar. So, the selector that searches within the block DOM node of course won't work on mobile.

Fix will be to change it so that we use the parent editor locator on mobile, and the block locator on desktop. I'll spin up that PR now 👍

**Comment by worldomonation** [comment]
> Secondly, there were a few desktop failures in the past few days, but if you look at the artifacts, there's actually a bug -- there are like 4 different AI input fields! 😱 But, this is now consistently fixed.

Nice investigation, thanks - it's nice to know our E2E caught a real bug, unintentionally. Maybe we should add this to the list of things caught by E2Es this week.

**Comment by worldomonation** [comment]
Related: https://github.com/Automattic/jetpack/issues/33444
