### ISSUE TITLE
Flaky E2E: Site Editor Smoke Test: Open the Page template

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#82637]
### Spec file

specs/fse/fse__temp-smoke-test.ts

### TeamCity ID

10903007

### Logs

```
======= Failed test run #1 ==========
  Error: Timed out waiting for the Editor canvas
  at EditorComponent.canvas (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-component.ts:60:10)
      at FullSiteEditorPage.waitUntilLoaded (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:126:24)
      at FullSiteEditorPage.prepareForInteraction (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:148:4)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__temp-smoke-test.ts:102:3)
======= Failed test run #2 ==========
  Error: Timed out waiting for the Editor canvas
  at EditorComponent.canvas (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-component.ts:60:10)
      at FullSiteEditorPage.waitUntilLoaded (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:126:24)
      at FullSiteEditorPage.prepareForInteraction (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/full-site-editor-page.ts:148:4)
      at Object.<anonymous> (/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/fse/fse__temp-smoke-test.ts:102:3)
```

![image](https://github.com/Automattic/wp-calypso/assets/6549265/06b33eb6-461b-4ac8-91f4-6f2bb2111585)

![image](https://github.com/Automattic/wp-calypso/assets/6549265/e37470c2-9e33-4791-9a41-3a4cb7d90f61)

**Comment by worldomonation** [comment]
@dpasque Does the timeline here line up with when you were running the user cleanup script?

**Comment by dpasque** [comment]
@worldomonation I'm pretty sure this is the same as this issue: https://github.com/Automattic/wp-calypso/issues/82412

I don't believe the user cleanup would have caused this!

**Comment by worldomonation** [comment]
Oh, didn't see that task you filed, my bad!
