### ISSUE TITLE
Jetpack E2E: Jetpack Earn (Atomic: php-new): Add and configure blocks in the editor: Pay with PayPal: Add the block from the sidebar

### ISSUE THREAD

**Issue by worldomonation** [Automattic/wp-calypso#83692]
### Spec file

test/e2e/specs/blocks/blocks__jetpack-earn.ts

### Logs

```
======= Failed test run #1 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').frameLocator('iframe[name="editor-canvas"]').locator('.editor-styles-wrapper').locator(':is(div[aria-label="Block: Pay with PayPal"].is-selected, div[aria-label="Block: Pay with PayPal"].has-child-selected)') to be visible
  ============================================================
  at EditorGutenbergComponent.waitFor [as getSelectedBlockElementHandle] (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-gutenberg-component.ts:155:17)
      at EditorPage.addBlockFromSidebar (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:321:4)
      at Object.<anonymous> (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:58:26)
======= Failed test run #2 ==========
  locator.waitFor: Timeout 10000ms exceeded.
  =========================== logs ===========================
  waiting for locator('body.block-editor-page').frameLocator('iframe[name="editor-canvas"]').locator('.editor-styles-wrapper').locator(':is(div[aria-label="Block: Pay with PayPal"].is-selected, div[aria-label="Block: Pay with PayPal"].has-child-selected)') to be visible
  ============================================================
  at EditorGutenbergComponent.waitFor [as getSelectedBlockElementHandle] (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/components/editor-gutenberg-component.ts:155:17)
      at EditorPage.addBlockFromSidebar (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/lib/pages/editor-page.ts:321:4)
      at Object.<anonymous> (/home/teamcity-4/buildAgent/work/c4a9d5b38c1dacde/test/e2e/specs/blocks/shared/block-smoke-testing.ts:58:26)
```

**Comment by worldomonation** [comment]
Something changed on 2023/10/30 between 23:35 and 23:51:

![image](https://github.com/Automattic/wp-calypso/assets/6549265/a4e78031-2e93-4938-8a19-15fc6179d9f2)

**Comment by worldomonation** [comment]
The current Pay with Paypal block looks a bit...different? And it also is no longer a `<figure>` with associated `aria-label` attributes.

![image](https://github.com/Automattic/wp-calypso/assets/6549265/f4ad31ba-8801-4289-bd4b-573e17db26b4)

**Comment by worldomonation** [comment]
Was caused by https://github.com/Automattic/jetpack/pull/33895 and resolved by reverting.
