### ISSUE TITLE
issues in webpack.config 

### ISSUE THREAD

**Issue by avatarr** [Automattic/wp-calypso#868]
Error: Cannot find module 'webpack.config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/external "webpack.config":1:1)
    at __webpack_require__ (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/webpack/bootstrap b8f3d566b47877e0cb1f:19:1)
    at Object.<anonymous> (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/server/bundler/index.js:9:18)
    at __webpack_require__ (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/webpack/bootstrap b8f3d566b47877e0cb1f:19:1)
    at setup (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/server/boot/index.js:34:13)
    at Object.<anonymous> (/Users/dev/Documents/software Dev/wp-calypso/build/webpack:/index.js:15:8)
make: *** [run] Error 1

How do I pass in this error?

**Comment by ehg** [comment]
Hey, this looks like it's caused by a space in your path. e.g. 'software Dev'. See #100.
