### ISSUE TITLE
[Calypso] `TypeError: config.isEnabled is not a function` on boot

### ISSUE THREAD

**Issue by kbariotis** [Automattic/wp-calypso#9684]
#### Steps to reproduce
1. Clone the latest master branch
2. Followed the install instructions
3. Run `make run`
4.

#### What I expected
The app to start

#### What happened instead

```
/Users/Bariotis/www/forks/wp-calypso/server/devdocs/bin/generate-components-usage-stats.js:42
	if ( ! config.isEnabled( 'devdocs/components-usage-stats' ) ) {
	              ^

TypeError: config.isEnabled is not a function
    at main (/Users/Bariotis/www/forks/wp-calypso/server/devdocs/bin/generate-components-usage-stats.js:42:16)
    at Object.<anonymous> (/Users/Bariotis/www/forks/wp-calypso/server/devdocs/bin/generate-components-usage-stats.js:192:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
make: *** [server/devdocs/components-usage-stats.json] Error 1
```

And if I output the `config` variable will contain the contents of the `config/development.json` file. No `isEnabled` function.

#### Browser / OS version

MacOS SIera

**Comment by hoverduck** [comment]
I'll leave it to a bigger Calypso expert than me to say for sure, but it looks like you have something overwriting the `config` package.  It should be pointing to https://www.npmjs.com/package/config

https://github.com/Automattic/wp-calypso/blob/master/server/devdocs/bin/generate-components-usage-stats.js#L11

Echoing it to the screen just before the line in your error message for me yields

```js
{ [Function: config]
  isEnabled: [Function: isEnabled],
  anyEnabled: [Function: anyEnabled] }
```
